### ISSUE TITLE
Cluster on route transition 

### ISSUE THREAD

**Issue by paullryan** [Wykks/ngx-mapbox-gl#10]
When you transition to a new route with 1.0.0.beta.3 and you have a cluster on a geoJSON source the current behavior is to remove the source with results in 
```
mapbox-gl.js:546 Error: Source "properties" cannot be removed while layer "clusters" is using it.
    at t.removeSource (mapbox-gl.js:406)
    at e.removeSource (mapbox-gl.js:520)
    at ngx-mapbox-gl.js:470
```

If feels like you have fixed this with the new cluster mechanism for beta.4 + but I haven't been able to test it yet.

**Comment by Wykks** [comment]
Hi! 
Thanks for reporting this issue !

I don't think it's related to cluster. This error is from mapbox-gl v0.43.0, (right now ngx-mapbox-gl only support the version 0.42.2 as set in `peerDependencies`).

I'll see how to handle that properly. Currently Angular call ngOnDestroy of the source first. Which was ok until mapbox-gl team decided to throw an error when a source is removed whereas some layers are using it.

**Comment by paullryan** [comment]
Interesting, I'll think on it too. Thanks for the quick response.

**Comment by Wykks** [comment]
I fixed this by adding a buffer of source and layer, and actually remove almost right away (in the same VM turn) in a defined order.
I always wanted to do something like this, because it also make it so nothing is called when we just want to remove the map.
For example, if you have a map with lots of (html) markers, and you just want to remove the map; ngx-mapbox-gl was removing all makers one by one before destroying the map. It's no longer the case !

**Comment by sprattek** [comment]
I'm having the same issue as @HarelM with only difference that I'm using 'mgl-image-source' and changing the coordinates dynamically.
```
<mgl-image-source
  id="floorplanImageSource"
  [url]="floorplanImageSourceOptions.url"
  [coordinates]="floorplanImageSourceOptions.coordinates"
></mgl-image-source>
<mgl-layer
  id="floorplanImageLayer"
  source="floorplanImageSource"
  type="raster"
  [paint]="floorplanImageLayerOptions.paint"
  [layout]="floorplanImageLayerOptions.layout"
></mgl-layer>
```

So after doing this in my component
```
this.floorplanImageSourceOptions.coordinates = newCoodinates
```
it throws me the same errors
