### ISSUE TITLE
@types/mapbox-gl@0.52.0 does not exit

### ISSUE THREAD

**Issue by LouAdrien** [Wykks/ngx-mapbox-gl#103]
Hello, and thanks for the great work with this library!
Following the readme instruction, you instruct : 

`npm install @types/mapbox-gl@0.52.0 --save-dev`

--> This fails, as the version 0.52 is not available for @types/mapbox-gl, using npm without version will install the latest one, i.e @types/mapbox-gl@0.51.4.
The install works, but then using mapbox types inside the code fails. For example, just declaring :

`  onLoad(mapInstance: Map) {}`

Will throw error : 

> error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).

Any ideas on which version to get exactly / how to solve this issue?? 
Thanks a lot in advance!

**Comment by Wykks** [comment]
Hi !

README fixed !
About the Map issue, it's because you're using the global es6 Map type. Add this import :
```
import { Map } from 'mapbox-gl';
```
and it should be fine :slightly_smiling_face:
