### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by gDev95** [Wykks/ngx-mapbox-gl#108]
Reference to [#7957](https://github.com/mapbox/mapbox-gl-js/issues/7957) and [my stackoverflow post](https://stackoverflow.com/questions/54863822/unable-to-preventdefault-inside-passive-event-listener-invocation-when-scrolli)

Get a Bunch of errors in console. Was not able to reproduce it.
map.html
```
<div class="map" [class.compact]="compact">
  <mgl-map [style]="'mapbox://styles/mapbox/streets-v9'" [maxZoom]="12" [minZoom]="2">
    <mgl-control mglNavigation></mgl-control>
  </mgl-map>
```
map.scss 
```
.map {
  height: 100%;
  width: 100%;

  mgl-map {
    height: 100%;
    width: 100%;
  }
```

and in parent component
```
 <div class="map-section" [class.side]="layoutState.desktop.spaceForMap && !layoutState.mapMode">
    <app-search-results-header *ngIf="layoutState.desktop.spaceForMap" [showLeftSection]="layoutState.mapMode" [showRightSection]="true"></app-search-results-header>

    <app-map
      [visible]="layoutState.desktop.spaceForMap || layoutState.mapMode"
      [mapExpanded]="layoutState.mapMode"
      [compact]="layoutState.vehicleHits.columnMode === 'compact'"
    ></app-map>
 </div>
```
parent.scss
```
  .map-section {
    position: absolute;
    display: flex;
    flex-direction: column;
    right: -$min-map-width;
    width: $min-map-width;
    height: 100%;
    transition: all 300ms $material-animation;

    &.side {
      right: 0;
      width: calc(28% + 120px);
    }

    app-search-results-header {
      background-color: $color-white;
    }

    app-map {
      height: 100%;
    }
  }
```

**Comment by dmytro-gokun** [comment]
@gDev95 Is this question still relevant? If yes, plz try building a minimal reproduction project using the latest version of ngx-mapbox-gl and i will try to help

**Comment by IKondor** [comment]
I have same issue after adding metrics (Yandex metrica) on my app
May be they capturing some click events and this produce errors (on hundreds in my case)
So I think the problem is not in your repo

**Comment by Bi-do-mi** [comment]
If you use Yandex. Metrica, just set false for the parameter value: accurateTrackBounce: false
