### ISSUE TITLE
Feature request: Popup to support custom classNames

### ISSUE THREAD

**Issue by d0tkom** [Wykks/ngx-mapbox-gl#111]
The mapbox popup component have this feature already built in, and would be nice if we could use it here as well.
<img width="874" alt="screenshot 2019-03-05 at 10 37 27" src="https://user-images.githubusercontent.com/5752211/53795696-cb1b7600-3f32-11e9-9ca0-c5ed175289b2.png">

**Comment by dmytro-gokun** [comment]
@d0tkom This have been implemented.
