### ISSUE TITLE
Question: default style for the marker component

### ISSUE THREAD

**Issue by dmytro-gokun** [Wykks/ngx-mapbox-gl#114]
Here: https://github.com/Wykks/ngx-mapbox-gl/blob/master/projects/ngx-mapbox-gl/src/lib/marker/marker.component.ts

we can see this piece of CSS:

```
    .mapboxgl-marker {
      line-height: 0;
    }
```
does anybody know what was the rational behind adding that?

**Comment by Wykks** [comment]
I.. don't really remember :sweat_smile:

It was maybe useful in the past. I think we can remove this now.

**Comment by dmytro-gokun** [comment]
@Wykks Gotcha. Do you want me to submit a PR? I'll do some smoke testing as well to see if removing that line that ruins the entire library :D

**Comment by Wykks** [comment]
I noticed that there's a small change here: https://wykks.github.io/ngx-mapbox-gl/demo/drag-a-marker, with `line-height` and without it.
If you have the time to figure which one is correct, that would be cool :+1:

**Comment by dmytro-gokun** [comment]
@Wykks Yep, i will work on that. Most likely over the weekend.

**Comment by dmytro-gokun** [comment]
@Wykks Okay, i've done some detective work here :)

This style was initially added by you 1st of May, 2018: https://github.com/Wykks/ngx-mapbox-gl/commit/550f665
The comment to the commit reads: fix(marker): remove line-height as it can incorrectly change the height (thus the position) of a marker.

Now, why does line-height affects the height of the marker? That is because of two reasons:
1) In your "drag-a-marker" example you do not have any content inside <mgl-marker></mgl-marker>;
2) As of consequence this code is executed (map.service.ts, line 271):

```
 if (marker.markersOptions.element.childNodes.length > 0) {
      options.element = marker.markersOptions.element;
    }

```
3) Thus, we are not providing any HTML element for the marker. Then, the default behavior kicks in, as described here https://docs.mapbox.com/mapbox-gl-js/api/#marker:

options.elementHTMLElement? | DOM element to use as a marker. The default is a light blue, droplet-shaped SVG marker

4) Aha! So, mapbox-gl will create a div for us and put the default droplet-shaped svg to that div! Now, svg is an inline element. Thus, it will obey line-height (and, probably, vertical-align as well) settings to calculate the of the parent element. The default line-height is 20px (as set in mapbox-gl\dist\mapbox-gl.css, at line 2).

5) So, it happens that mapbox-gl has a bug with placement of a default marker! The proper fix for that bug would be to set "display: block" for that default SVG element.

Conclusion: I will go ahead and create a bug report/pull request for mapbox-gl project. When it's merged/released, we'll be able to remove this line-height hack from ngx-mapbox-gl.

**Comment by dmytro-gokun** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/8071

**Comment by Wykks** [comment]
Nice work!
So it seems that I noticed that issue before, but I was probably in the middle of something so I quick fixed it, without further investigations 😄

**Comment by dmytro-gokun** [comment]
@Wykks Yep, exactly. All credit goes to you :). I think we can remove this hack when they release a new version. So, let's keep this issue open for a while.

**Comment by dmytro-gokun** [comment]
@Wykks https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.54.0:

Fixed a bug where default HTML marker positioning was slightly off. #8074

https://github.com/mapbox/mapbox-gl-js/pull/8074

So, after update to 0.54.0 we should remove this hack and document that in the chagelog, as it's a breaking change.
