### ISSUE TITLE
fitBoundsOptions zooms to entire world

### ISSUE THREAD

**Issue by arturhun** [Wykks/ngx-mapbox-gl#117]
```
    "@angular/core": "^7.2.9",
    "mapbox-gl": "0.52.0",
    "ngx-mapbox-gl": "^3.0.1",
    ...
    "@types/mapbox-gl": "^0.51.4",
```

I have the following code:

```html
<mgl-map
  [style]="'mapbox://styles/mapbox/streets-v9'"
  [fitBounds]="sweBounds"
  [fitBoundsOptions]="sweBoundsOptions"
>
</mgl-map>
```

```ts
sweBounds = [[10.5930952, 55.1331192], [24.1776819, 69.0599699]];
sweBoundsOptions = {offset: 50}; // {padding: {top: 100, bottom: 100}};
```

`sweBounds` worked fine only until I added `fitBoundsOptions` which made the map zoom to entire world. Seems like any of the available syntax used for padding or offset screws up the zoom.

I have looked into #74 - I have my options initialized staticaly. Should I initialize them in a different way?

**Comment by Wykks** [comment]
Hi !

`offset` is not a number, and for `padding` you must set left and right too.
https://docs.mapbox.com/mapbox-gl-js/api/#map#fitbounds

Also, I updated ngx-mapbox-gl to use the bounds option (from mapbox-gl 0.53.0) for initial view.
