### ISSUE TITLE
Why is layer source attribute init only?

### ISSUE THREAD

**Issue by LouAdrien** [Wykks/ngx-mapbox-gl#119]
Hello, first thanks for the amazing work, these bindings are extremely useful.

My question is : why does the "source" setting of the mgl layer is only possible at the init time?
There are many use cases where someone would need to change a layer source data according to some logic. Are there some restrictions that would prevent such a use case?

Thanks in advance,

**Comment by Wykks** [comment]
Hi!

Afaik, mapbox-gl doesn't provide a way to update the source of a layer. The only way to implement this would be to remove/re-add the layer.
This pattern has proven to cause issues https://github.com/Wykks/ngx-mapbox-gl/issues/139, so it's going to stay like that until mapbox-gl implement a updateLayer method.

For now, you can create multiple layers and use *ngIf to switch the source for example.

(sorry for the late response..)
