### ISSUE TITLE
error in wiki

### ISSUE THREAD

**Issue by Methodician** [Wykks/ngx-mapbox-gl#12]
Hi there, me again...

Found another problem with the docs. I've never edited a github wiki before but it seems maybe I don't have privilege?

Anyway, your sample code here: https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation#example-1 

source needs to be in square brackets (at least for me anyway) I was using a polygon.
```
...
<mgl-map
  ...
>
  <mgl-layer
    id="state-borders"
    type="line"
    [source]="states"
    [paint]="{
      'line-color': '#627BC1',
      'line-width': 2
    }"
  ></mgl-layer>
</mgl-map>
```

**Comment by Wykks** [comment]
Yes indeed, fixed! Thanks :)
