### ISSUE TITLE
Layer on top of layer, two click-events

### ISSUE THREAD

**Issue by magnusev** [Wykks/ngx-mapbox-gl#124]
Hey,

First, absolutly awesome work!

I have this case where I will have many layers over each other (a polygon, then another polygon then a lot of points). The issue I have is when I click the point the clickhandler from all the other layers under also happen. I want different things to happen based on what layer you press. Is there a way to find out if other events triggered? (or gather all click-events into one event, so I can write some logic on it)? (I use geoJson sources)

**Comment by dmytro-gokun** [comment]
@magnusev Is this still relevant? If yes, plz provide a reproduction (stackblitz) using latests versions of ngx-mapbox-gl/mapbox-gl.
