### ISSUE TITLE
Edit functionality in documentation is not giving the right results

### ISSUE THREAD

**Issue by HarelM** [Wykks/ngx-mapbox-gl#125]
First and foremost, thanks a lot for this great library!
When surfing to the io page of the documentation and using the edit toggle button to see the code only the `main.ts` file is displayed, which is probably not what was intended:
![image](https://user-images.githubusercontent.com/3269297/55136059-0d9d3080-5136-11e9-8aa8-b63656b21687.png)
I couldn't find a way to see the code of the relevant example.

**Comment by Wykks** [comment]
Yes, I noticed this few days ago.
I'll try to look into it in the next few days :)
