### ISSUE TITLE
mgl-control order problem

### ISSUE THREAD

**Issue by HarelM** [Wykks/ngx-mapbox-gl#126]
If have the following code:
```
   <mgl-control position="top-left">1</mgl-control>
   <mgl-control position="top-left" *ngIf="true">2</mgl-control>
   <mgl-control position="top-left">3</mgl-control>
```
Which creates an incorrect ordered of controls:
![image](https://user-images.githubusercontent.com/3269297/55196599-880e9480-51b8-11e9-8879-ce320afc529d.png)

Removing the `*ngIf` sort this out, but this is a silly example, as I need this `*ngIf` in real life.
Also I've tried to place a control under the scale in case the scale control is in the right bottom and couldn't...
This is probably due to the same reason, i.e:
The following two snippets produce the same controls layout:
```
<mgl-control position="bottom-right">2</mgl-control>
<mgl-control mglScale position="bottom-right"></mgl-control>
```
and:
```
<mgl-control mglScale position="bottom-right"></mgl-control>
<mgl-control position="bottom-right">2</mgl-control>
```
![image](https://user-images.githubusercontent.com/3269297/55196842-5649fd80-51b9-11e9-8055-2172666bb5aa.png)

Let me know if there's something I can do to help out.

**Comment by sroettering** [comment]
I have this issue, too. See https://github.com/Wykks/ngx-mapbox-gl/issues/75

**Comment by HarelM** [comment]
@sroettering yup, this issue can be closed as a duplicate. Can you elaborate on the workaround you did as I have no workaround right now beside not using `mgl-control` and using regular css to solve this.

**Comment by sroettering** [comment]
I had two options in mind as a workaround:
1. Use flexbox ordering to order the controls on the map
2. Use the onLoad event and add the controls "by hand" with: map.addControl(new FullscreenControl())

Option 1 is good if you are ok with changing the mapbox styling.
With option 2, you would have to add all controls in the same corner like this.

**Comment by BAByrne** [comment]
Another workaround is to add `*ngIf="true"` to the other controls.

**Comment by HarelM** [comment]
I've ended up using an id element and `ViewChildern` like so:
HTML:
```<zoom #topLeftControl></zoom>```
TS:
```js
...
@ViewChildren("topLeftControl", { read: ElementRef })
 public topLeftControls: QueryList<ElementRef>;
...
public onLoad() {
    this.topLeftControls.forEach(c => {
            this.mapComponent.mapInstance.addControl(new CustomControl(c.nativeElement), "top-left");
        });
}
```
And so I have full control on the order, option @sroettering 's option 2 basically.

**Comment by dmytro-gokun** [comment]
@BAByrne I do not think there is a way to solve this 'properly' because (Angular does not give any ordering guaranetees). At least not one I could be able to come up with. If you have any idea have this might be solved - let me know (plz open a separate issue) or submit a PR.
