### ISSUE TITLE
clusterProperties feature not supported in mgl-geojson-source

### ISSUE THREAD

**Issue by remoteriver** [Wykks/ngx-mapbox-gl#130]
It seems clusterProperties is not currently supported in mgl-geojson-source,
is there any other ways to get aggregating values from clustered points?
Thanks a lot

**Comment by Crylion** [comment]
I am currently facing the same issue. I would need to pass along some properties of my individual features to the clusters and the correct way to do so in Mapbox seems to be the clusterProperties attribute of the source

**Comment by thhet** [comment]
Is seems, "clusterProperties" is available with @types/mapbox-gl in version 1.10.2 .

**Comment by dmytro-gokun** [comment]
@thhet Is there still an issue when using the latest version of the library & @types/mapbox-gl?
