### ISSUE TITLE
clickTolerance is missing from map initialization options

### ISSUE THREAD

**Issue by HarelM** [Wykks/ngx-mapbox-gl#135]
It would be nice to be able to change the value of `clickTolerance` when initializing a map.
See documentation:
https://docs.mapbox.com/mapbox-gl-js/api/

**Comment by tamim-khan** [comment]
I can work on this one

**Comment by dmytro-gokun** [comment]
@tamim-khan That would be great!

**Comment by dmytro-gokun** [comment]
Released as part of https://github.com/Wykks/ngx-mapbox-gl/releases/tag/v4.1.0
@tamim-khan Thanks again for your help!
