### ISSUE TITLE
Problems with setup

### ISSUE THREAD

**Issue by LarBearrr** [Wykks/ngx-mapbox-gl#136]
I have been trying to get this setup with a new Angular CLI project and am having several issues. So far, I have been able to get the basic map to display, but any other examples are not working, specifically the locate user example. Here is my setup:

```
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.3.5
Node: 10.15.0
OS: win32 x64
Angular: 7.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/build-webpack     0.13.5
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cli                      7.3.5
@ngtools/webpack                  7.3.5
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
```

`app.module.ts`
```
import { NgxMapboxGLModule } from 'ngx-mapbox-gl';
import { MapComponent } from './components/map/map.component';
...
imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    RouterModule.forRoot(appRoutes),
    FlashMessagesModule.forRoot(),
    NgxMapboxGLModule.withConfig({
      accessToken: 'ACCESSTOKEN', // Optionnal, can also be set per map (accessToken input of mgl-map)

    })
  ],
```

`angular.json`
```
"styles": [
              "src/styles.css",
              "node_modules/mapbox-gl/dist/mapbox-gl.css",
              "node_modules/@mapbox/mapbox-gl-geocoder/lib/mapbox-gl-geocoder.css"
            ],
```

The first issue I had was a console error saying `global is undefined` and I was able to fix this by adding `(window as any).global = window;` to my `polyfill.ts` file.

I also ran into was importing the styles. When trying to add them to my `angular.json` I was receiving an error that the module could not be found, specifically the `mapbox-gl-geocoder.css` which made me realize this package was never included in the setup instructions, so I brought it in. However, this does not seem to do the trick:

Also, I don't see a way to include the styles with the `ng serve` command? It would be helpful to specify what is meant by "global css," if this references the `app.component.css` file or the `styles.css` file.

Regardless, I also created a MapComponent following the example:

`map.component.css`
```
mgl-map {
    height: 100%;
    width: 100%;
}
```

`map.component.html`
```
<mgl-map
    [style]="'mapbox://styles/mapbox/streets-v9'"
    [zoom]="[9]"
    [center]="[-74.50, 40]"
  >
</mgl-map>
```

and imported this into my HomeComponent:
```
import { Component, OnInit } from '@angular/core';

import { MapComponent } from '../map/map.component'

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```
```
<app-map></app-map>
```
Importing the `mapbox-gl.css` file into `styles.css` seems to produce something:

![image](https://user-images.githubusercontent.com/28734844/56085684-cd63d080-5e0c-11e9-84e4-89c54e0a60fe.png)

I was also just able to get the locate user example working. However, I am concerned that the geocoder will not work properly.

**Comment by SystemOrb** [comment]
Same for me, anyone can fix this?

**Comment by mechevarria** [comment]
Thanks for the tip on the polyfill add. Unless the polyfill issue is fixed, that should be added to the setup instructions

**Comment by suchrita** [comment]
I am also facing same , please help if anybody knows how to fix

**Comment by Wykks** [comment]
Hi!

Indeed, the setup instructions needs some update.

I was not aware about the global issue (that definitly wasn't happening before...), I'll investigate what's going on there.

**Comment by dmytro-gokun** [comment]
@Wykks Oops. That was me responsible for that not-documented polyfill :(. Sorry. Unfortunately, it is required, because some library which is referenced by mapbox wants it here. I might be wrong, but in previous versions Angular provided this polyfill by default, but later it was removed for some reason (discussed here, for example: https://stackoverflow.com/questions/50734437/window-as-any-global-window). May be it was a better idea to implement this automatically in the lib, so if "global" is not here, then it is added. But i did not feel it was a right task for ngx-mapbox-gl to do that.

In any case, thanks a lot for updating the documentation!

**Comment by Wykks** [comment]
Indeed, I recall seeing something like that here https://github.com/Wykks/ngx-mapbox-gl/commit/ed6634c569d7aec7db09dea710ac365a114eb57c#diff-9e517f3fcf9c40ebc0e391f319472ed2R66 but didn't pay enough attention to it :smile: 

For now, let's leave it like that, and keep this issue open as a reminder to improve this situation :)

**Comment by LarBearrr** [comment]
@Wykks Just doing some cleanup with my open issues. Did you still want to leave this open?
