### ISSUE TITLE
Changing mgl-image-source coordinates dynamically causes issues

### ISSUE THREAD

**Issue by sprattek** [Wykks/ngx-mapbox-gl#139]
I'm having the same issue as @HarelM at #10  with only difference that I'm using 'mgl-image-source' and changing the coordinates dynamically.
```
<mgl-image-source
  id="floorplanImageSource"
  [url]="floorplanImageSourceOptions.url"
  [coordinates]="floorplanImageSourceOptions.coordinates"
></mgl-image-source>
<mgl-layer
  id="floorplanImageLayer"
  source="floorplanImageSource"
  type="raster"
  [paint]="floorplanImageLayerOptions.paint"
  [layout]="floorplanImageLayerOptions.layout"
></mgl-layer>
```

So after doing this in my component
```
this.floorplanImageSourceOptions.coordinates = newCoodinates
```
it throws me these errors

`Source "floorplanImageSource" cannot be removed while layer "floorplanImageLayer" is using it.`
And then `There is already a source with this ID`

_Originally posted by @sprattek in https://github.com/Wykks/ngx-mapbox-gl/issues/10#issuecomment-482495116_

**Comment by Wykks** [comment]
In lots of Inputs of source, I'm doing a 
```
this.ngOnDestroy();
this.ngOnInit();
```
I knew this was not super smart :sweat_smile: 
I don't remember when mapbox-gl did this change but yep, it doesn't work anymore.
I'll try to find a way around this or simply move theses inputs as "Init inputs" only.

**Comment by Wykks** [comment]
Note: there's a new `updateImage` method, in mapbox-gl v0.54.0. I'll update the image component accordingly. (the image component is one of the few component using this bad pattern destroy/init).

**Comment by dmytro-gokun** [comment]
@Wykks As far as i can see. for imageSource there are some methods to update it after creation: https://docs.mapbox.com/mapbox-gl-js/api/#imagesource
I'll try to use those.

**Comment by Wykks** [comment]
Yep I was refering to that in my previous post :)
Not sure to have the time this week, so would be great if you can take a look.

Other components probably don't have a magical update method (I searched them before making this bad pattern), so I guess we can only changes input from dynamic to init only (for v4).

**Comment by dmytro-gokun** [comment]
@Wykks Yep, i'll try to work on this shortly
