### ISSUE TITLE
Feature: Add support for specific mouse button drag only on markers

### ISSUE THREAD

**Issue by ANullBoolean** [Wykks/ngx-mapbox-gl#140]
Allow us to define which mouse button we want to use for dragging. Currently, it allows any mouse button to drag a marker.

**Comment by dmytro-gokun** [comment]
@ANullBoolean From what i see mapbox-gl itself does not support this. Thus, we cannot support it in this library which is a thin wrapper around mapbox-gl. Thus, i'm closing this issue.

If you think i'm wrong, plz comment here and show me the way to do it with pure mapbox-gl. Then we'll think.
