### ISSUE TITLE
click event inside popup is not triggered

### ISSUE THREAD

**Issue by iusmanali** [Wykks/ngx-mapbox-gl#143]
I have a feature layer and i'm showing a popup on mouseenter event. 
`mapInstance.on("mouseenter", "scoots_layers", function (e) {
      var _lat = e.lngLat.lat;
      var _lng = e.lngLat.lng;
      var coordinates = [_lng, _lat];
      this.popup = new Popup({
        closeButton: true,
        closeOnClick: true,
      });
      this.popup.setLngLat(coordinates)
        .setHTML('<button (click) ="goToPage()">Hello</button>')
        .addTo(mapInstance);
    });`

But the click event is not firing anyhow from button click.

**Comment by vamcs** [comment]
You don't have Angular loaded in the pop-up, that's why (click) won't work.

**Comment by iusmanali** [comment]
> You don't have Angular loaded in the pop-up, that's why (click) won't work.

Thank you for your reply. I have solved by using anchor tag and setting href attribute and it's working fine
