### ISSUE TITLE
Missing option to enable antialiasing

### ISSUE THREAD

**Issue by wilmervanheerde** [Wykks/ngx-mapbox-gl#148]
The mgl-map component is missing an option to enable antialiasing as specified by the Mapbox GL API https://docs.mapbox.com/mapbox-gl-js/api/#map

**Comment by Wykks** [comment]
This options has been added in mapbox-gl v0.54.0 (https://github.com/mapbox/mapbox-gl-js/pull/7821).

ngx-mapbox-gl currently support mapbox-gl v0.53.1 (https://github.com/Wykks/ngx-mapbox-gl/blob/master/projects/ngx-mapbox-gl/package.json#L25)

**Comment by wilmervanheerde** [comment]
Thanks for your answer. Is there an indication when ngx will support this version?

**Comment by Wykks** [comment]
Maybe at the end of this month. I'm planning to make a new release to support Angular 8.
