### ISSUE TITLE
How can i add icon-image in Angular 6+

### ISSUE THREAD

**Issue by dashtaki** [Wykks/ngx-mapbox-gl#150]

**Comment by dashtaki** [comment]
I wanna load image name from .geojaon file and show it in map but it does not work.

```
{
          'id': 'icons',
          'type': 'symbol',
          'source': 'G_Rahro_source',
          'zoom': 16,
          'layout': {
            // 'icon-image': './assets/images/map/{ICON_TYPE}.png',
            // 'icon-image': 'ICON_TYPE.png ',
            'icon-image': '/../../../assets/images/map/{ICON_TYPE}.png',
            // 'icon-image': 'D:/Workspaces/Front-MallManagement/src/assets/data/map/{ICON_TYPE}.png',
            'icon-size': 40,
            'icon-allow-overlap': true,
          },
```

**Comment by Wykks** [comment]
Hi! You cannot do that directly. 
Load the image first : https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation#mgl-image-mapbox-gl-api
And than you can set with `icon-image`, with the image id.

(`mgl-image` is a wrapper of https://docs.mapbox.com/mapbox-gl-js/api/#map#addimage).

You may want to generate image 'ondemand' with `styleimagemissing` (https://github.com/mapbox/mapbox-gl-js/pull/7987).
(Not sure if this event is currently exposed in ngx-mapbox-gl... yet 😅 )
