### ISSUE TITLE
mapboxgl popup style not changing

### ISSUE THREAD

**Issue by SaltyPotato** [Wykks/ngx-mapbox-gl#156]
Hello,

I'm trying to edit the mapbox-gl popup style using css, but it does not change!

I'm trying these styles on the popup box:
`
.mapboxgl-popup {
    top: -15px!important;
}

.mapboxgl-popup-tip {
    display:none!important;
}

.mapboxgl-popup-content {
    text-align: center;
    font-family: 'Open Sans', sans-serif;

}

.mapboxgl-popup-content > div > ul {
    list-style: none;
}
`

With this html:

`<mgl-popup [marker]="markerRef">
                    <ul>
                            <li>Test? Test</li>
                            <li>Test? Testing</li>
                    </ul>
                </mgl-popup>`

On inspect element it doesn't even list the styles.

**Comment by Wykks** [comment]
Hi!
If you are putting this css inside a component css, it's not a bug, it's a feature 😄 
Angular limit the scope of the css to the component view only. 
The class `.mapboxgl-popup` isn't inside your component view.

So you have two options:
Put a div inside popup, than you can style it properly (recommended way):

```
<mgl-popup [marker]="markerRef">
<div class="my-popup">
  <ul> <li>Test? Test</li> <li>Test? Testing</li> </ul>
</div>
</mgl-popup>
```

Or use `::ng-deep` operator to disable css encapsulation (keep :host in front of ::ng-deep to limit the scope of your css):
```
:host ::ng-deep .mapboxgl-popup {
top: -15px!important;
}```

(You also can add your css in a global css file, like style.css).

I guess I could add class support directly in `mgl-popup`. I'll see if it's a good idea.

**Comment by dmytro-gokun** [comment]
@SaltyPotato Besides the solutions mentioned above, `mgl-popup` now has a `className` property.
