### ISSUE TITLE
Missing popup options in interface

### ISSUE THREAD

**Issue by vincentlessardcgi** [Wykks/ngx-mapbox-gl#164]
Can you add the options to the PopupOptions interface in the api : https://docs.mapbox.com/mapbox-gl-js/api/#popup!

At least the maxWidth option, it works.

node_modules/@types/mapbox-gl/index.d.ts

Thx in advance

**Comment by BAByrne** [comment]
maxWidth is added in PR #180

**Comment by dmytro-gokun** [comment]
@vincentlessardcgi This is available now, after v4.0.0 was released
