### ISSUE TITLE
Configuring mapboxgl.baseApiUrl ?

### ISSUE THREAD

**Issue by denisa** [Wykks/ngx-mapbox-gl#167]
Our app might need to configure the **baseApiURL** (https://github.com/mapbox/mapbox-gl-js/blob/e71afb6ac6096ae7ddabf439fc3539759a9f0a87/src/index.js#L69-L71) and we don't see how to do this?

**Comment by RodrigoMattosoSilveira** [comment]
Denis and I are colleagues. I found a solution using _[ngx] customMapboxApiUrl: string Change url of mapbox:// (set config.API_URL)_

**Comment by Wykks** [comment]
Yep that's what you were looking for :)
