### ISSUE TITLE
Feature request: ability to specify a class name for a marker

### ISSUE THREAD

**Issue by dmytro-gokun** [Wykks/ngx-mapbox-gl#171]
Sometimes there is a need to manipulate the style of a marker's component content div. For example, z-index: https://github.com/Wykks/ngx-mapbox-gl/issues/105

While there is a known workaround, it's a bit clumsy. It would be much easier if it were possible to specify a 'className' on the <mgl-marker> itself.

@Wykks I'll create a PR.

**Comment by Wykks** [comment]
I often hesitated to do this, but yeah it makes sense :)

**Comment by dmytro-gokun** [comment]
@Wykks Yeah, i actually found myself doing this workarounds and did not like :)
