### ISSUE TITLE
Is there an option to set a marker for GeoCoder?

### ISSUE THREAD

**Issue by dhermyt** [Wykks/ngx-mapbox-gl#174]
Hi,

I'm looking at this scenario:
https://docs.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/

How can I set the marker property? Will it be exposed on the TS file?

**Comment by zoocreative** [comment]
Hey @dhermyt just wondering if you got this working. I can add the geocoder and input an address using searchInput which is great but there is no marker for the location...am i missing something obvious?

**Comment by dhermyt** [comment]
@zoocreative I did it like this

```
<mgl-control class="search-box" mglGeocoder 
(result)="onGeocoderResult($event)" types="address"></mgl-control>
```

and inside the onGeocoderResult you just add the popup (or marker) programatically

```
new Popup()
      .setLngLat(location)
      .setDOMContent(contentContainer)
      .addTo(this.map);
```

**Comment by zoocreative** [comment]
Hi @dhermyt 

Thanks for the info, very useful. I had just realised that would be the answer and was coming back here to update my comment but glad to see you have done it :)

Thanks for the quick response and for the help :)
