### ISSUE TITLE
v3.3.1 and Angular 7.1.0

### ISSUE THREAD

**Issue by dimitrilahaye** [Wykks/ngx-mapbox-gl#175]
Hello there!
Can I pass my project on version 3.3.1 without breaking Angular 7?
Currently I'm on `ngx-mapbox-gl` 2.0.0, `mapbox-gl` 0.51.0 and `Angular` 7.1.0
Thanks for the answer!

**Comment by Wykks** [comment]
Hi!

I tested v3.x against Angular 7.2, but 7.1 should be fine :)

**Comment by dmytro-gokun** [comment]
@dimitrilahaye Is this question still relevant?

**Comment by dimitrilahaye** [comment]
No it isn’t, I will come back to you if there is any problem ;) thanks !
