### ISSUE TITLE
Error occurred while parsing your function triggers

### ISSUE THREAD

**Issue by kzbar** [Wykks/ngx-mapbox-gl#176]
Angular CLI: 8.1.1
Node: 10.15.3

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.1
@angular-devkit/build-angular              0.801.1
@angular-devkit/build-optimizer            0.801.1
@angular-devkit/build-webpack              0.801.1
@angular-devkit/core                       7.3.9
@angular-devkit/schematics                 7.3.9
@angular/cdk                               8.0.2
@angular/fire                              5.2.1
@angular/http                              7.2.15
@angular/material                          8.0.2
@ngtools/webpack                           8.1.1
@nguniversal/common                        8.1.1
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        7.3.9
@schematics/update                         0.801.1
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.35.2

ReferenceError: self is not defined
    at xxxxxx\node_modules\mapbox-gl\dist\mapbox-gl.js:29:4978
    at define (xxxxxx\node_modules\mapbox-gl\dist\mapbox-gl.js:22:5)
    at xxxxxx\node_modules\mapbox-gl\dist\mapbox-gl.js:33:1
    at xxxxxx\node_modules\mapbox-gl\dist\mapbox-gl.js:3:81
    at Object.<anonymous> (xxxxxx\node_modules\mapbox-gl\dist\mapbox-gl.js:6:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by Wykks** [comment]
Hi!

I will need a bit more information than a stacktrace of mapbox-gl :sweat_smile:

**Comment by dmytro-gokun** [comment]
@kzbar Do you still have a problem? If yes, plz try building a minimal reproduction project (stackblitz etc.) that one can grab and check. Otherwise, it's very unlikely anyone will help you.

**Comment by dmytro-gokun** [comment]
Closing this because of no reproduction information was provided. If you still have an issue/question, feel free to open a new issue and provide more details.
