### ISSUE TITLE
Country Constraint

### ISSUE THREAD

**Issue by encinitasLab** [Wykks/ngx-mapbox-gl#178]
When using the geocoder control it does not appear to be applying the country when making the request.  Viewing through the console it shows the following call
https://api.mapbox.com/geocoding/v5/mapbox.places/en.json?limit=5&proximity=-117.1432%2C32.76458&access_token=xxxx

but is missing country param
https://api.mapbox.com/geocoding/v5/mapbox.places/en.json?limit=5&proximity=-117.1432%2C32.76458&access_token=xxxx  **&country=US**

Sample implementation below (proximity is passed along as expected)
<mgl-map
      [style]="selectedStyle"
      [zoom]="[startingZoom]"
      [center]="[startingLongitude, startingLatitude]"
      (load)="mapLoadedHandler($event)"
      (moveEnd)="moveEndHandler($event)"
      (moveStart)="moveStartHandler($event)"
    >
      <mgl-control
        mglGeocoder
        [proximity]="[startingLongitude, startingLatitude]"
        **[country]="'US'"**
      >
      </ mgl-control>
    </ mgl-map>

Screen of result with United Kingdom in response
![image](https://user-images.githubusercontent.com/53234544/61738210-ab001e00-ad3e-11e9-8c1d-9783b1c67b82.png)

**Comment by dhermyt** [comment]
Look at my PR https://github.com/Wykks/ngx-mapbox-gl/pull/177

**Comment by dmytro-gokun** [comment]
@encinitasLab Can you plz verify if this works after v4.0.0 release?

**Comment by encinitasLab** [comment]
It is working as expected now.  Thanks for the help all!  @dmytro-gokun , @dhermyt 
![image](https://user-images.githubusercontent.com/53234544/66867673-a23f7280-ef50-11e9-959a-5f80002a1d14.png)
