### ISSUE TITLE
contextmenu event does not return MapMouseEvent data

### ISSUE THREAD

**Issue by michaelsivo** [Wykks/ngx-mapbox-gl#181]
Hello,

When I'm using the contextmenu event on mgl-map, only the default MouseEvent is returned. I have tested click and dlbClick, they return correctly the MapMouseEvent.

My mgl-map looks like this:
`<mgl-map class="map"
        id="mgl-map"
        [style]="(tileSource$|async)"
        [zoom]="zoom"
        [center]="(center$|async)"
        (load)="onMapLoaded($event)"
        (idle)="onMapIdle(mglLayers, layers)"
        (zoomEnd)="onZoomEnd(zoom)"
        (mouseMove)="updateCurrentInfos($event)"
        (click)="openContextMenu($event)"
        (contextmenu)="openContextMenu($event)"
        [preserveDrawingBuffer]="true">
      >`

When I use click event, I have the following result:
![image](https://user-images.githubusercontent.com/15062083/63265652-69578a00-c28e-11e9-9f89-5d2d50e8472c.png)

And with the context menu, I have this:
![image](https://user-images.githubusercontent.com/15062083/63265711-81c7a480-c28e-11e9-92ae-fe60343ec6a9.png)

Angular: 9.0.0
mapbox: 0.54.0
ngx-mapbox: 3.3.0

**Comment by BAByrne** [comment]
Make sure to use camelcase (`contextMenu`) on the [outputs](https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation#outputs).

**Comment by michaelsivo** [comment]
Yep, that worked thanks!
