### ISSUE TITLE
ivy breaks mgl-control

### ISSUE THREAD

**Issue by abheyshah** [Wykks/ngx-mapbox-gl#182]
When i enable ivy, mgl-control (mglGeocoder) fails on instantiation without it it works fine.

**Comment by jrrembert** [comment]
Also seeing this in Angular 8.2.14 (both with and without Ivy, all possible directives).

Will try to create a small reproducible example this weekend.

**Comment by dmytro-gokun** [comment]
@jrrembert There is a geocoder example on demo site: https://wykks.github.io/ngx-mapbox-gl/demo/mapbox-gl-geocoder which is built using Angular 8.2.14. It appears to work just fine. Plz compare your code to the demo's code. 

In any case, the reproduction is really welcome.

**Comment by dmytro-gokun** [comment]
I'm closing this because of no answer. If someone else experiences this issue with latest version, plz open a new issue and attach a reproduction
