### ISSUE TITLE
Changing mgl-canvas-source coordinates dynamically causes issues

### ISSUE THREAD

**Issue by Eduardsson** [Wykks/ngx-mapbox-gl#183]
Same problem as in #139 is with mgl-canvas-source. When you change coordinates you get `Source "canvasSource" cannot be removed while layer "canvasLayer" is using it.`

**Comment by dmytro-gokun** [comment]
@Eduardsson Can you confirm that this issue still exists with v4.0.0? If yes, could you plz build a minimal reproduction, so it's easier investigate?
