### ISSUE TITLE
Draw mgl-circle using data-driven meters value

### ISSUE THREAD

**Issue by smartman21cen** [Wykks/ngx-mapbox-gl#188]
I am going to draw data-driven meters circle using mgl-radius.
<mgl-layer
            id="trade-circle"
            type="circle"
            source="tradecircles-source"
            [paint]="{
              'circle-radius': {
                stops: [
                  [0, 0],
                  [20, ['get', 'radius']]
                ],
                base: 2
              },
              'circle-color': '#00ff00',
              'circle-stroke-color': ['get', 'circle-stroke-color'],
              'circle-stroke-width': 2
            }"
          ></mgl-layer>

but got this error.

mapbox-gl.js:29 Error: layers.trade-circle.paint.circle-radius.stops[1][1]: expressions are not allowed in function stops.

**Comment by dmytro-gokun** [comment]
The error code is pretty clear: "expressions are not allowed in function stops.". You need to consult mapbox-gl-js documentation about that. May be you just need to reference a newer version of mapbox-gl-js which does support expressions in function stops (if such version exists).

NB. I think, https://github.com/mapbox/mapbox-gl-js would be a proper place to ask this question. Or, even better, stackoverflow.
