### ISSUE TITLE
mglGeocoder css style problem

### ISSUE THREAD

**Issue by ykamchi** [Wykks/ngx-mapbox-gl#189]
Hi,

I am using mgl-map with the search control, by adding the tag:  <mgl-control mglGeocoder></mgl-control> to the <mgl-map> tag.

The problem is that styling is missing to the search control and it looks like you can see in the attached picture.

I included "node_modules/@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css" in my style section in angular.json, but when I am checking this file, it is missing some styles, for example: the class "geocoder-pin-right" is missing.

I prefer not to upgrade my packages if not needed ... currently I am using:
    "@mapbox/leaflet-pip": "^1.1.0",
    "@mapbox/mapbox-gl-draw": "^1.1.2",
    "@mapbox/mapbox-gl-geocoder": "^4.5.0",
    "mapbox-gl": "^0.54.0",
    "ngx-mapbox-gl": "^3.3.1",
    "@types/mapbox-gl": "^0.51.10",

  I would appreciate your assistance, and thanks for the good work that you are doing :)

Thx,
Yohay
![Screenshot from 2019-10-20 23-44-16](https://user-images.githubusercontent.com/13556774/67165947-965e1100-f393-11e9-8476-fd878858e4bf.png)

**Comment by dmytro-gokun** [comment]
One thing i can notice is that you are referencing mapbox-gl-geocoder ^4.5.0 and ngx-mapbox-gl has not been updated to that version yet (it might have breaking changes). However, this is a wild shot. If you want someone to spend time helping you, plz build a minimal reproduction project that one can try compiling, modifying etc.

**Comment by dmytro-gokun** [comment]
@ykamchi Is this question still relevant ? Have you found a fix? If yes, please share it.

**Comment by ykamchi** [comment]
Dmytro, I still have this problem, but I did not have the time to create the example code that you asked. Please leave this open for few more days and I will do my best to create a simple example. Thanks!!

**Comment by dmytro-gokun** [comment]
sure

**Comment by StArBuLLeT** [comment]
Hi, im experiencing the same problem

<img width="401" alt="Screen Shot 2019-12-03 at 5 42 29 PM" src="https://user-images.githubusercontent.com/36328157/70039193-79546900-15f4-11ea-85a0-d22ccb92a12e.png">

**Comment by StArBuLLeT** [comment]
Hi, im currently experiencing the same problem, im showing the map inside a modal

<img width="401" alt="Screen Shot 2019-12-03 at 5 42 29 PM" src="https://user-images.githubusercontent.com/36328157/70039521-14e5d980-15f5-11ea-9199-72b466427ca1.png">

**Comment by sroettering** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/2598613/71169146-8c07a880-2258-11ea-89c4-ca4c314fd2e6.png)

ngx-mapbox-gl: 4.3.0
@mapbox/mapbox-gl-geocoder: 4.5.1
mapbox-gl: 1.6.1

Using @mapbox/mapbox-gl-geocoder: 4.0.0 works fine though.

**Comment by dmytro-gokun** [comment]
@sroettering Yes, as i said mapbox-gl-js has not been updated to use the latest mapbox-gl-geocoder yet. If someone wants to help with that - they are welcome.

**Comment by ThomasAlanParker** [comment]
Hello, I was able to provide some help. Here is a project with a reproduction of the issue.

I would love to be of further assistance and I'll be comparing the code from both versions.

[gccss-project.zip](https://github.com/Wykks/ngx-mapbox-gl/files/3990954/gccss-project.zip)

**Comment by ThomasAlanParker** [comment]
After more testing this issue arose between the 3.1.6 and 4.0.0 versions, I'll investigate the css changes and report back what I learn.

**Comment by pra2win** [comment]
Use below style which I have borrowed from the demo example

/*
======================================================================================
Geocoder custome style
======================================================================================
*/
//geocoder style
.mapboxgl-ctrl-geocoder,
.mapboxgl-ctrl-geocoder *,
.mapboxgl-ctrl-geocoder :after,
.mapboxgl-ctrl-geocoder :before {
	box-sizing: border-box
}

.mapboxgl-ctrl-geocoder {
	font: 15px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
	position: relative;
	background-color: #fff;
	width: 33.3333%;
	min-width: 240px;
	max-width: 360px;
	z-index: 1;
	border-radius: 3px
}

.mapboxgl-ctrl-geocoder input[type=text] {
	font-size: 12px;
	width: 100%;
	border: 0;
	background-color: transparent;
	height: 40px;
	margin: 0;
	color: rgba(0, 0, 0, .5);
	padding: 10px 10px 10px 40px;
	text-overflow: ellipsis;
	white-space: nowrap;
	overflow: hidden
}

.mapboxgl-ctrl-geocoder input:focus {
	color: rgba(0, 0, 0, .75);
	outline: 0;
	box-shadow: none;
	outline: dotted thin\8
}

.mapboxgl-ctrl-geocoder .geocoder-icon-search {
	position: absolute;
	top: 10px;
	left: 10px
}

.mapboxgl-ctrl-geocoder button {
	padding: 0;
	margin: 0;
	background-color: #fff;
	border: none;
	cursor: pointer
}

.mapboxgl-ctrl-geocoder .geocoder-pin-right * {
	background-color: #fff;
	z-index: 2;
	position: absolute;
	right: 10px;
	top: 10px;
	display: none
}

.mapboxgl-ctrl-geocoder,
.mapboxgl-ctrl-geocoder ul {
	box-shadow: 0 0 0 2px rgba(0, 0, 0, .1)
}

.mapboxgl-ctrl-geocoder ul {
	background-color: #fff;
	border-radius: 0 0 3px 3px;
	left: 0;
	list-style: none;
	margin: 0;
	padding: 0;
	position: absolute;
	width: 100%;
	top: 100%;
	z-index: 1000;
	overflow: hidden;
	font-size: 12px
}

.mapboxgl-ctrl-bottom-left .mapboxgl-ctrl-geocoder ul,
.mapboxgl-ctrl-bottom-right .mapboxgl-ctrl-geocoder ul {
	top: auto;
	bottom: 100%
}

.mapboxgl-ctrl-geocoder ul>li>a {
	clear: both;
	cursor: default;
	display: block;
	padding: 5px 10px;
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
	border-bottom: 1px solid rgba(0, 0, 0, .1);
	color: #404040
}

.mapboxgl-ctrl-geocoder ul>li:last-child>a {
	border-bottom: none
}

.mapboxgl-ctrl-geocoder ul>li>a:hover {
	color: #202020;
	background-color: #f3f3f3;
	text-decoration: none;
	cursor: pointer
}

.mapboxgl-ctrl-geocoder ul>li.active>a {
	color: #202020;
	background-color: #e3e3e3;
	text-decoration: none;
	cursor: pointer
}


.geocoder-icon {
	display: inline-block;
	width: 20px;
	height: 20px;
	vertical-align: middle;
	speak: none;
	background-repeat: no-repeat
}

.geocoder-icon-search {
	background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCIgdmVyc2lvbj0iMS4xIj4NCiAgPHBhdGggZD0iTTguNSA0QzYgNCA0IDYgNCA4LjUgNCAxMSA2IDEzIDguNSAxMyA5LjQgMTMgMTAuMiAxMi44IDEwLjggMTIuM0wxMC45IDEyLjMgMTQuMyAxNS43QzE0LjUgMTUuOSAxNC43IDE2IDE1IDE2IDE1LjYgMTYgMTYgMTUuNiAxNiAxNSAxNiAxNC43IDE1LjkgMTQuNSAxNS43IDE0LjNMMTIuMyAxMC45IDEyLjMgMTAuOEMxMi44IDEwLjIgMTMgOS40IDEzIDguNSAxMyA2IDExIDQgOC41IDR6TTguNSA1LjVDMTAuMiA1LjUgMTEuNSA2LjggMTEuNSA4LjUgMTEuNSAxMC4yIDEwLjIgMTEuNSA4LjUgMTEuNSA2LjggMTEuNSA1LjUgMTAuMiA1LjUgOC41IDUuNSA2LjggNi44IDUuNSA4LjUgNS41eiIgZmlsbD0iIzAwMCIvPg0KPC9zdmc+)
}

.geocoder-icon-close {
	background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMCAyMCIgdmVyc2lvbj0iMS4xIiBoZWlnaHQ9IjIwIiB3aWR0aD0iMjAiPg0KICA8cGF0aCBkPSJtNSA1IDAgMS41IDMuNSAzLjUtMy41IDMuNSAwIDEuNSAxLjUgMCAzLjUtMy41IDMuNSAzLjUgMS41IDAgMC0xLjUtMy41LTMuNSAzLjUtMy41IDAtMS41LTEuNSAwLTMuNSAzLjUtMy41LTMuNS0xLjUgMHoiIGZpbGw9IiMwMDAiLz4NCjwvc3ZnPg==)
}

.geocoder-icon-loading {
	background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgd2lkdGg9IjIwIiBoZWlnaHQ9IjIwIiB2aWV3Qm94PSIwIDAgMjAgMjAiPjxwYXRoIGQ9Im0xMCAyIDAgMy4zYzIuNiAwIDQuNyAyLjEgNC43IDQuN2wzLjMgMGMwLTQuNC0zLjYtOC04LTh6IiBmaWxsPSIjMDAwIi8+PHBhdGggZD0iTTEwIDJDNi44IDIgMy43IDQuMSAyLjYgNy4xIDEuNCAxMCAyLjEgMTMuNiA0LjUgMTUuOGMyLjQgMi40IDYuNCAyLjkgOS40IDEuMiAyLjUtMS40IDQuMi00LjIgNC4yLTctMS4xIDAtMi4yIDAtMy4zIDAgMC4xIDIuMi0xLjcgNC4zLTMuOCA0LjZDOC43IDE1IDYuNCAxMy44IDUuNyAxMS43IDQuOCA5LjcgNS42IDcuMSA3LjYgNiA4LjMgNS42IDkuMSA1LjMgMTAgNS4zYzAtMS4xIDAtMi4yIDAtMy4zeiIgc3R5bGU9ImZpbGw6IzAwMDtvcGFjaXR5OjAuMiIvPjwvc3ZnPg==);
	-webkit-animation: .4s linear infinite rotate;
	animation: .4s linear infinite rotate
}

**Comment by ThomasAlanParker** [comment]
> Use below style which I have borrowed from the demo example

This is great Pravin, what demo example did you find this in? Thanks!

**Comment by pra2win** [comment]
@ThomasAlanParker I did some analysis on HTML generated by geocoder and it seems that the style is not for that HTML its version issue.

Today I have a better solution for that install below version of the geocoder

Import CSS in style.css
`@import '~@mapbox/mapbox-gl-geocoder/lib/mapbox-gl-geocoder.css';`

Here is a working example: 
https://stackblitz.com/edit/angular-m2dqxa?file=src/app/app.component.html
