### ISSUE TITLE
Errors when import MapService

### ISSUE THREAD

**Issue by Gubernskiy** [Wykks/ngx-mapbox-gl#19]
I am using ngx-mapbox-gl:1.0.0-beta.5 and I can't import MapService to my component. If i write like this 
```
import {MapService} from 'ngx-mapbox-gl/src/app/lib/map/map.service';
```
i have an error while compiling 
```
Module not found: Error: Can't resolve 'ngx-mapbox-gl/src/app/lib/map/map.service' 
```
if i change import to 
```
import {MapService} from 'ngx-mapbox-gl/bundles/ngx-mapbox-gl.umd.js';
```

Compiled successfully. But i have errors in browser console like
```
core.js:1440 ERROR Error: Uncaught (in promise): Error: Can't resolve all parameters for MyComponent:
```

I think that it is an error in ng-packagr or something with it's config. Because if i use your source files in my app everything is fine and work as expected.

**Comment by Wykks** [comment]
Hi!

This is done on purpose. `MapService` is *private*. Why do you need it ?

**Comment by Gubernskiy** [comment]
I have made my own custom component for app. And put it inside mgl-map to have the same instance of MapService. I am using some functions from it and mapinstance property.

**Comment by Wykks** [comment]
What are you using from `MapService` exactly ? It's not made to be used by something else than ngx-mapbox-gl itself.
I you want to use fonction from mapbox-gl directly you can get the map instance with the `load` event of `mgl-map`.

**Comment by Gubernskiy** [comment]
i am using getCurrentViewportBbox(). I understand that i can calculate it from map instance directly. At first i thought to hook on load event and get map instance from there as you suggest. But i thought that it is not good idea because i would have to make a wrapper component with your map and my component and put some logic there using hooks. I just want my component to be like ```mgl-layer``` and others. They know nothing about the map and get all nesessary informathing inside theyself. If you think it's not good i'll think about another solluting.

**Comment by Wykks** [comment]
Yup, it's fine, I wanted to do a proper way to add custom component, in order to do some extension like a ngx-mapbox-gl-draw for example. For this use case, exposing the `MapService` seems correct.
I do want to make a stable documented api for that someday.

**Comment by shadower01** [comment]
Hi, in my component I injected the MapService but the mapInstance is empty. how should I inject it? thanks for sharing the ngx-mapbox-gl wrapper and thanks for your help.

I'm doing this.
-----my mapComponent
....
constructor(**private MapService: MapService**) { }

  fitToKenya() {
    this.MapService.**mapInstance**.fitBounds([[32.958984, -5.353521], [43.50585, 5.615985]]); // _ERROR!! mapInstance is null_
  }

----------app.module
.....
NgxMapboxGLModule.withConfig({ accessToken: '...this is ok..', geocoderAccessToken: '......' }), ],
entryComponents: [......],
  providers: [**MapService**, ...........],
  bootstrap: [AppComponent]

**Comment by Wykks** [comment]
@shadower01 You should use the load event to get the Map instance. See this example : 
https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation#example
`this.MapService.mapInstance` is not available when the map is not loaded yet (and you can't rely on angular lifecycle there).
(Also never provide MapService elsewhere than in a component meant to be used inside a mgl-map).

I won't say that it's not recommended. It's just about whenever or not you want to do something declaratively (using template) or imperatively (calling mapbox-gl function directly). And sometimes, things "feels" better imperatively.
