### ISSUE TITLE
Image overlay problem with mgl-geojson-source

### ISSUE THREAD

**Issue by smartman21cen** [Wykks/ngx-mapbox-gl#191]
I am going to add multi image overlay in mgl-map.

if I used mgl-geojson-source and mgl-layer raster overlay, error occured 
zone.js:192 Uncaught TypeError: Cannot read property 'bind' of undefined

and if using mgl-image-source, I can't change image source dynamically ( all data is changed dynamically like mgl-geojson-source & mgl-layer(fill) )
and image size should be fitted by coordinates ( not static size ).

I think it should be important function for mapbox.
Please check this issue, and let me know solution

**Comment by dmytro-gokun** [comment]
> if I used mgl-geojson-source and mgl-layer raster overlay, error occured
zone.js:192 Uncaught TypeError: Cannot read property 'bind' of undefined

Looks like there is a problem with your code. Please provide a project (or github refrence) which can be used to reproduce the issue and then someone may step in and help you.

> and if using mgl-image-source, I can't change image source dynamically ( all data is changed dynamically like mgl-geojson-source & mgl-layer(fill) ) ... 

Again, please provide reproduction for this issue.

> and image size should be fitted by coordinates ( not static size ). I think it should be important function for mapbox.

It should be fitted. Make sure you are providing correct parameters. Refer to mapbox documentation here: https://docs.mapbox.com/mapbox-gl-js/api/#imagesource

> Please check this issue, and let me know solution

This is an opensource project. If you want someone step in and help you, you need to provide means to reproduce your problem(s) easily. Otherwise, it is unlikely someone will help.

**Comment by smartman21cen** [comment]
Thanks for your reply Poi.coordinate.coordinates like this[[-84.5208446905212, 39.1113823971051], [-84.521520607193, 39.1113823971051], [-84.521520607193, 39.1118236064295], [-84.5208446905212, 39.1118236064295]]Poi.fence.coordinates like this[[[[-84.5208446905212, 39.1113823971051], [-84.521520607193, 39.1113823971051], [-84.521520607193, 39.1118236064295], [-84.5208446905212, 39.1118236064295]]]] Please check html file and let me know solution. Sent from Mail for Windows 10 From: Dmytro GokunSent: Thursday, November 7, 2019 12:26 AMTo: Wykks/ngx-mapbox-glCc: smartman21cen; AuthorSubject: Re: [Wykks/ngx-mapbox-gl] Image overlay problem with mgl-geojson-source (#191) if I used mgl-geojson-source and mgl-layer raster overlay, error occuredzone.js:192 Uncaught TypeError: Cannot read property 'bind' of undefinedLooks like there is a problem with your code. Please provide a project (or github refrence) which can be used to reproduce the issue and then someone may step in and help you.and if using mgl-image-source, I can't change image source dynamically ( all data is changed dynamically like mgl-geojson-source & mgl-layer(fill) ) ...Again, please provide reproduction for this issue.and image size should be fitted by coordinates ( not static size ). I think it should be important function for mapbox.It should be fitted. Make sure you are providing correct parameters. Refer to mapbox documentation here: https://docs.mapbox.com/mapbox-gl-js/api/#imagesourcePlease check this issue, and let me know solutionThis is an opensource project. If you want someone step in and help you, you need to provide means to reproduce your problem(s) easily. Otherwise, it is unlikely someone will help.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 
  
  

 0 ? ['match', ['get', 'id'], selected_pids, true, false] : false,
		'#00bcd4',
		['boolean', ['==', ['string', ['get', 'subCategoryId'], ''], '812930'], false],
		'#FFBB00',
		'#F65314'
	  ],
	  'fill-opacity': [
		'case',
		['boolean', ['feature-state', 'hover'], false],
		1,
		selected_pois.length > 0 ? ['match', ['get', 'id'], selected_pids, true, false] : false,
		0.8,
		0.5
	  ]
	}"
	[filter]="['all',
	  ['!', ['boolean', ['get', 'hidden'], false]],
	  ['!=', ['string', ['get', 'subCategoryId'], ''], 'PK0005'],
	  filters.operators.length > 0 ? ['match', ['get', 'operatorId'], filters.operators, true, false] : true
	]"
>

 0 ? ['match', ['get', 'operatorId'], filters.operators, true, false] : true
	]"
>

**Comment by dmytro-gokun** [comment]
Please use https://stackoverflow.com to ask questions. Only post bug reports and feature requests here.

**Comment by smartman21cen** [comment]
Same size in another zoomHow can fix it?Will wait good solution from you.Best reagards. Sent from Mail for Windows 10 From: Dmytro GokunSent: Thursday, November 7, 2019 12:26 AMTo: Wykks/ngx-mapbox-glCc: smartman21cen; AuthorSubject: Re: [Wykks/ngx-mapbox-gl] Image overlay problem with mgl-geojson-source (#191) if I used mgl-geojson-source and mgl-layer raster overlay, error occuredzone.js:192 Uncaught TypeError: Cannot read property 'bind' of undefinedLooks like there is a problem with your code. Please provide a project (or github refrence) which can be used to reproduce the issue and then someone may step in and help you.and if using mgl-image-source, I can't change image source dynamically ( all data is changed dynamically like mgl-geojson-source & mgl-layer(fill) ) ...Again, please provide reproduction for this issue.and image size should be fitted by coordinates ( not static size ). I think it should be important function for mapbox.It should be fitted. Make sure you are providing correct parameters. Refer to mapbox documentation here: https://docs.mapbox.com/mapbox-gl-js/api/#imagesourcePlease check this issue, and let me know solutionThis is an opensource project. If you want someone step in and help you, you need to provide means to reproduce your problem(s) easily. Otherwise, it is unlikely someone will help.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
