### ISSUE TITLE
Map ts/html

### ISSUE THREAD

**Issue by ZdenekPoznerJr** [Wykks/ngx-mapbox-gl#192]
Hello, im quite new to mapbox but I've created a map in html something like this..

  <mgl-map
  [style]="'https://map.urbido.cz/styles/basic/style.json'"
  [zoom]="[10]"
  [center]="[18.1638, 49.831]"
  [cursorStyle]="cursorStyle"
  >

But now i need to address this HTML map in my .ts file. How do i do this?  I really need to call resize because my map is bugging out. All I have is   map :  Map; and an Import import { LngLat, Map, NavigationControl } from 'mapbox-gl';

**Comment by dmytro-gokun** [comment]
Please use https://stackoverflow.com to ask questions. Only post bug reports and feature requests here.
