### ISSUE TITLE
[QUESTION] Map screenshot from another tab gives me a blank image

### ISSUE THREAD

**Issue by dimitrilahaye** [Wykks/ngx-mapbox-gl#194]
**ngx-mapbox-gl version**: 3.3.1

### Question
I think it is a problem with WebGL, and I've already asked this question to the mapbox-gl repo, but I would need your opinion.
On my current project, I have an asynchronous task which initialize a map with settings from backend, in order to generate an image file from map's container.
The issue happens during the process, if the user navigate into another tab in his browser, the generated final image is blank.
In order to have a right screenshot, he needs to let the application's tab active.

Have you ever faced this kind of problem?

**Comment by dmytro-gokun** [comment]
@dimitrilahaye Frankly, I do not think this has anything to do with what ngx-mapbox-gl does. Must be WebGL or browser issue (have you tried different browsers?)

**Comment by dimitrilahaye** [comment]
Yes I tried on Firefox and Chrome, same issue. I will investigate in WebGL. Thanks for the fast answer :)
