### ISSUE TITLE
Demo website has broken scripts and styles paths - https://wykks.github.io/ngx-mapbox-gl

### ISSUE THREAD

**Issue by mojesto** [Wykks/ngx-mapbox-gl#195]
![mapbox](https://user-images.githubusercontent.com/6073086/69445365-d6316300-0d5a-11ea-9df3-0819e2042f77.png)

**Comment by dmytro-gokun** [comment]
Than you for reporting this, @mojesto! I'll look at it shortly

**Comment by dmytro-gokun** [comment]
@mojesto This should be fixed now. Again, thanks for heads up, good catch 👍
