### ISSUE TITLE
Map interactivity is not to update dynamically

### ISSUE THREAD

**Issue by mojesto** [Wykks/ngx-mapbox-gl#196]
@Component({
  selector: 'showcase-demo',
  template: `
  <button (click)="toggleInteractive()">{{ isInteractive }}</button>

  <mgl-map
    [style]="'mapbox://styles/mapbox/streets-v9'"
    [interactive]="isInteractive"
    [zoom]="[9]"
    [center]="[-74.50, 40]"
  >
  </mgl-map>
  `,
  styleUrls: ['./examples.css']
})
export class DisplayMapComponent {
  isInteractive = false;

  toggleInteractive() {
    this.isInteractive = !this.isInteractive;
  }
}

**Comment by dmytro-gokun** [comment]
This property is "init only" as specified here: https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation#mgl-map-mapbox-gl-api. The reason for that is mapbox itself does not support changing this property after a map is created.
