### ISSUE TITLE
Marker are shown above popup

### ISSUE THREAD

**Issue by abrass** [Wykks/ngx-mapbox-gl#198]
I have some markers positioned on the map. I added a popup to them with ng-container. Everything is fine. I only struggle, that the other markers are shown above the mgl-popup and I have no idea how to increase the render priority of that popup. Is there any option? 

![Bildschirmfoto 2019-11-26 um 15 20 54](https://user-images.githubusercontent.com/3006610/69641366-5d831d00-1060-11ea-9012-1a76104e1286.png)
`<ng-container *ngFor='let emergencyExit of emergencyExits$ | async;'>

	<mgl-marker #emergencyExitMarker
                [lngLat]="[emergencyExit.longitude, emergencyExit.latitude]"
                anchor="bottom">
		<div class="emergency-exit">
			...
		</div>
	</mgl-marker>
	<mgl-popup [marker]="emergencyExitMarker"
               class="emergency-exit-popup"
               [closeButton]="false"
               [anchor]="'top'"
    >
	    <div class="emergency-exit-content">
        {{emergencyExit.name}} ({{emergencyExit.type}})
</div>
	</mgl-popup>
</ng-container>`

**Comment by dmytro-gokun** [comment]
I think the reason for that is the order in which they are defined. If you mentally 'unwrap' the 'ngFor' you will see that the 2nd marker is defined after the 1st popup and so on. Try having popups in a separate 'ngFor' after markers. Let us know if that works.

**Comment by abrass** [comment]
Hey,

in this implementation with ng-container the popup must reference an existing marker. If I put the definition of the popup above the marker I get an error, that #emergencyExitMarker cannot be referenced. 

If I seperate the definitions in own *ngFor and use lat,long definitions the issue stays the same.

Do you have any other ideas? I'll check if maybe my own styling of the popup may cause the problem.

Cheers

Anton

**Comment by dmytro-gokun** [comment]
@abrass Nice you found the solution (Y)

> I still have the issue that I want the search marker to be always above the other markers.

Markers have a property called className. Try setting that to "myClassName" and doing this in your CSS:

```
.mapboxgl-marker.myClassName {
      z-index: 666;
}
```

**Comment by abrass** [comment]
Dear dmytro-gokun,

that works really great for the z-positioning of my markers. Thank you a lot!

After that I had the issue that my popup is shown behind that markers again.

I fixed it by additionally add an z-index to the mapbox-gl-class, which finally was that class-set working for me:
`.mapboxgl-marker.emergency-exit-marker-z {
  z-index: 1;
}
.mapboxgl-marker.device-marker-z {
  z-index: 2;
}
.mapboxgl-marker.search-marker-z {
  z-index: 3;
}
.mapboxgl-popup {
  position: absolute;
  top: 0;
  left: 0;
  display: flex;
  will-change: transform;
  pointer-events: none;
  z-index: 4;
}
`

**Comment by abrass** [comment]
I found one last issue with that topic. I use  <mgl-marker-cluster> with  <ng-template mglPoint let-feature> and <ng-template mglClusterPoint let-feature>.

Is it possible to set the z-index there as well?

**Comment by dmytro-gokun** [comment]
As far as I know there is not "built-in" way to do that. But you can check sourcecode yourself and see if you find a gap to squeeze in

**Comment by abrass** [comment]
thx for your help and time!
