### ISSUE TITLE
TypeError: Cannot read property 'removeControl' of undefined

### ISSUE THREAD

**Issue by sroettering** [Wykks/ngx-mapbox-gl#199]
After the fix for the control ordering problem there seems to be a new bug now.
I have a screen size dependent custom control that I want to hide on small screens. So I attach an `*ngIf` on it and expect it to work properly.
However, when running on a screen where the control should actually be hidden, an error is thrown. It seems that the `MapService` can't remove the control because the `mapInstance` is not yet defined.

**Comment by dmytro-gokun** [comment]
@sroettering Thanks for reporting this. This might actually be the case.. Do you mind spending some time to build a small reproduction? Thanks.

**Comment by sroettering** [comment]
Sure I will create a stackblitz example when I find the time.

**Comment by sroettering** [comment]
Unfortunately I was not able to reproduce the issue in a stackblitz example. Seems to be a very specific usecase. However, I guess an additional check for the mapInstance being defined before calling removeControl on it would not hurt.

**Comment by sroettering** [comment]
I was able to fix my issue now, but unfortunately still was not able to reproduce it in a simple stackblitz.
Basically my setup is the following:
I have two different maps where either one shows depending on an ngIf with async pipe (breakpointObserver from material in my case).
Each map has a set of different controls, but only a single control was causing the issue.
This control itself has an ngIf on it which was also depending on the same observable as the two maps just one level deeper and via normal component input.
Inside this control are two different buttons each with an ngIf as well rendering when the other one doesn't.

I found that multiple subscriptions to the observable are causing the issue. So I included a simple shareReplay(1) in the stream and that fixed it.

From my perspective this issue can be closed for now.

**Comment by dmytro-gokun** [comment]
@sroettering Thank you for the investigation. I will keep this open for now, as i probably need to revisit 'removeControl' call like you suggested.

**Comment by SpiegelSoft** [comment]
I think this issue is breaking my jasmine tests.

**Comment by dmytro-gokun** [comment]
I was able to reproduce and fix this. Please check out https://github.com/Wykks/ngx-mapbox-gl/releases/tag/v4.8.1
