### ISSUE TITLE
Cannot render some SVG's in Layer

### ISSUE THREAD

**Issue by kendallmark3** [Wykks/ngx-mapbox-gl#201]
We are trying to render svg's in the <mgl-layer> see below- we are setting the layout and paint properties in code-see below- some SVG's do not show up on map and not getting an error- can we trap for the error to see why they will not show?

<div>
  <mgl-geojson-source id="pointSource" [data]="pointsGeoJson">
  </mgl-geojson-source>
  <mgl-layer
    id="pointLayer"
    type="symbol"
    source="pointSource"
    (click)="onClick($event)"
    [layout]=layoutstr
    [paint]=paintstr
  >
  </mgl-layer>
  <app-point-popup
    [selectedPoint]="selectedPoint"
    [mapID]="mapID"
    [masterLogoArray]="masterLogoArray"
  ></app-point-popup>
</div>

<div>
  <mgl-geojson-source id="pointSource" [data]="pointsGeoJson">
  </mgl-geojson-source>
  <mgl-layer
    id="pointLayer"
    type="symbol"
    source="pointSource"
    (click)="onClick($event)"
    [layout]=layoutstr
    [paint]=paintstr
  >
  </mgl-layer>
  <app-point-popup
    [selectedPoint]="selectedPoint"
    [mapID]="mapID"
    [masterLogoArray]="masterLogoArray"
  ></app-point-popup>
</div>

=================code

public layoutstr = {
    'icon-size': 0.5,
    'icon-image': [
      'case',
      [
        'any',
        [
          '==',
          ['get', 'styleType', ['object', ['get', 'styleObject']]],
          'logo'
        ]
      ],
      ['get', 'lastLogoId', ['object', ['get', 'styleObject']]],
      [
        'concat',
        ['get', 'lastIconId', ['object', ['get', 'styleObject']]],
        '_',
        ['get', 'imageColor', ['object', ['get', 'styleObject']]]
      ]
  ],
    'text-field': ['get',
      [
      'case',
      [
        'any',
        [
          '==',
          ['get', 'type', ['object', ['get', 'styleObject']]],
          'individual'
        ],
        [
          '==',
          ['get', 'type', ['object', ['get', 'styleObject']]],
          'icon'
        ]
      ],
      'label',
      'order'
    ],
      ['object', ['get', 'attributes']]],
    'text-font': ['Arial Unicode MS Bold'],
    'text-size': [
      'case',
      [
        'any',
        ['==',
        ['get', 'lastIconId', ['object', ['get', 'styleObject']]],
        'defaultSymbol'],
        ['==',
        ['get', 'lastIconId', ['object', ['get', 'styleObject']]],
        'emptyIcon']
      ],
      14,
      0
    ],
    'icon-allow-overlap': true,
    'text-allow-overlap': true
  };

  public paintstr = {
    'text-color': '#ffffff',
    'icon-color': ['get', 'imageColor', ['object', ['get', 'styleObject']]],
    'icon-opacity': [
      'case',
      ['boolean', ['feature-state', 'hover'], false],
      0.6,
      1
    ]
  };

**Comment by dmytro-gokun** [comment]
@kendallmark3 Is this question still relevant? If yes, plz create a small stackblitz reproduction and we'll see if someone (may be I) can help.
