### ISSUE TITLE
Cluster Expansion Zoom (map.getSource('id').getClusterExpansionZoom(...)) method does not exist

### ISSUE THREAD

**Issue by zamansafari** [Wykks/ngx-mapbox-gl#203]
In my Angular app, I have created the cluster as stated in the example here (https://docs.mapbox.com/mapbox-gl-js/example/cluster/). However, map.getSource('myAssets').getClusterExpansionZoom(...) "getClusterExpansionZoom()" method does not exist in ngx-mapbox-gl. Any help would greatly be appreciated.

My package.json:
"mapbox-gl": "^0.54.0",
"ngx-mapbox-gl": "^3.3.1",
"@mapbox/mapbox-gl-draw": "^1.1.2",
"@mapbox/mapbox-gl-geocoder": "^3.1.6",
"@types/mapbox-gl": "^0.51.10"

![ngx-mapbox-gl-cluster-expansion-zoom-problem](https://user-images.githubusercontent.com/24205626/71805515-7fb48580-3077-11ea-9cda-c8526877bb27.png)

**Comment by Wykks** [comment]
Assuming `map` is the MapboxGl object, you should have this method when querying geojson source since https://github.com/mapbox/mapbox-gl-js/pull/6829

Is 'myAssets' a geojson source ?

Also If you use `mgl-geojson-source` you can access `getClusterExpansionZoom` there.
For example:
```
@ViewChild(GeoJSONSourceComponent) source: GeoJSONSourceComponent;
[...]
const zoom = await source.getClusterExpansionZoom(clusterId);
```

**Comment by dmytro-gokun** [comment]
@zamansafari Is this question still relevant? Does the issue still exist when using the latests version of the libs (ngx-mapbox-gl, mapbox-gl & @types/mapbox-gl)?

**Comment by zamansafari** [comment]
Although I have updated all mapbox-gl libs, but I still encounter the same "Property 'getClusterExpansionZoom' does not exist on type 'AnySourceImpl'." error problem. 
Belows are my libs version:
"@types/mapbox-gl": "^0.51.12",
"@mapbox/mapbox-gl-draw": "^1.2.0",
"@mapbox/mapbox-gl-geocoder": "^3.1.6",
"mapbox-gl": "^0.54.1",
"ngx-mapbox-gl": "^3.3.1",

Thank you in advance.

**Comment by zamansafari** [comment]
I have used mapbox-gl examples from the mapbox GL tutorial page in the below:

https://docs.mapbox.com/mapbox-gl-js/example/cluster/

**Comment by dmytro-gokun** [comment]
@zamansafari 

> "@types/mapbox-gl": "^0.51.12",
> "@mapbox/mapbox-gl-draw": "^1.2.0",
> "@mapbox/mapbox-gl-geocoder": "^3.1.6",
> "mapbox-gl": "^0.54.1",
> "ngx-mapbox-gl": "^3.3.1",

These are not the latest versions available. Use "npm outdated" to find out the latest versions.

**Comment by PriyaVarshney2387** [comment]
yes, still I am facing same issue

"@types/mapbox-gl": "2.1.1",
"mapbox-gl": "2.2.0",
`map.getSource('places').getClusterExpansionZoom(
                        clusterId,
                        function (err, zoom) {
                            if (err) {
                                return;
                            }
                            let center;
                            if (features[0].geometry.type === 'Point') {
                                center= features[0].geometry.coordinates;
                            }
                            map.easeTo({
                                center: center,
                                zoom: zoom
                            });
                        }
                    );`

**Comment by drushadrusha** [comment]
Found the solution, works fine for me.
`const source: mapboxgl.GeoJSONSource = map.getSource('earthquakes') as mapboxgl.GeoJSONSource source.getClusterExpansionZoom(...`

**Comment by lukaszbacik** [comment]
> Found the solution, works fine for me. `const source: mapboxgl.GeoJSONSource = map.getSource('earthquakes') as mapboxgl.GeoJSONSource source.getClusterExpansionZoom(...`

Yes, it works ;)

**Comment by rhysstubbs** [comment]
Regarding Types, what about the `serialize` function? 

```
const src = this._map.getSource( sourceName );

// Property 'serialize' does not exist on type 'AnySourceImpl' (same for any of the other types)
const srcData = src.serialize(); 
```

**Comment by abitoguna** [comment]
> Found the solution, works fine for me. `const source: mapboxgl.GeoJSONSource = map.getSource('earthquakes') as mapboxgl.GeoJSONSource source.getClusterExpansionZoom(...`

A quick workaround I did in addition to the fix above is

`
const geometry = features[0].geometry

map.easeTo({
     center: geometry?.coordinates,
      zoom: zoom,
});
`
