### ISSUE TITLE
MglMap.movingMethod has no apparent effect

### ISSUE THREAD

**Issue by mloffer** [Wykks/ngx-mapbox-gl#205]
Setting `movingMethod` to `jumpTo` does not disable animations.

```
<mgl-map
    [style]="'mapbox://styles/mapbox/streets-v9'"
    [zoom]="[9]"
    [center]="[-74.50, 40]"
    (load)="map = $event"
    movingMethod="jumpTo"
></mgl-map>
```

**Comment by mloffer** [comment]
Ah, this is really a shortcoming of the [Mapbox GL JS API](https://docs.mapbox.com/mapbox-gl-js/api/#map#fitbounds). 

Animations for fitBounds must be defined via fitBoundOptions. There's an [undocumented duration property](https://github.com/mapbox/mapbox-gl-js/issues/1473) that you can use to disable animations.

```
<mgl-map
    [fitBounds]=[-124.763068, 45.543541, -116.915989, 49.002494]
    [fitBoundsOptions]="{ duration: 0 }"
></mgl-map>
```

**Comment by dmytro-gokun** [comment]
@mloffer Thanks for sharing your findings!
