### ISSUE TITLE
Running Build with '--aot' results in errors with v2.x 

### ISSUE THREAD

**Issue by jpdhernandez** [Wykks/ngx-mapbox-gl#208]
![image](https://user-images.githubusercontent.com/16705958/73851928-557ff000-47fc-11ea-8878-ba3679179d13.png)

And when I add the optional tokens in this version we get this error:
![image](https://user-images.githubusercontent.com/16705958/73854010-cc6ab800-47ff-11ea-9f20-13bb28fcac10.png)

Please help!

**Comment by Wykks** [comment]
Hi !

Can you specify which version of angular are you using ? V2.x should works fine with Angular 6 & 7

**Comment by jpdhernandez** [comment]
@Wykks Hi I'm using Angular v 6.1.1.

**Comment by Wykks** [comment]
Hum that's weird. I created an angular 6 project with ng new (v6) and I do not reproduce.

Can you check if your dependencies looks like this ? : (`ng version`)
```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4
```
And 
```
    "mapbox-gl": "0.51.0",
    "ngx-mapbox-gl": "2.3.3",
[...]
     "@types/mapbox-gl": "0.51.0"
```

**Comment by dmytro-gokun** [comment]
@jpdhernandez If this question still relevant? If yes, please provide a reproduction project (a stackblitz would be ideal).

**Comment by jpdhernandez** [comment]
@dmytro-gokun @Wykks Thanks for looking into it. Question is no longer relevant. Closing.
