### ISSUE TITLE
Directions Support

### ISSUE THREAD

**Issue by vandres** [Wykks/ngx-mapbox-gl#212]
Hi,

Sorry if this is a beginner question.

Is there any plan on supporting the Directions API https://docs.mapbox.com/help/how-mapbox-works/directions/ ?

What is the esiest way to use the API by itself and still use your library as a core?

**Comment by TheKeithStewart** [comment]
@vandres What you can do is call the directions API and feed the geometry that it responds with back into a mgl-feature in a mgl-geojson-source component. It might look something like this:

```
    <mgl-geojson-source
      [id]="my-directions'"
    >
      <mgl-feature [geometry]="route.geometry"> </mgl-feature>
    </mgl-geojson-source>

    <mgl-layer
      [id]="my-directions"
      type="line"
      [source]="my-directions"
      [paint]="{
        'line-color': '#BF93E4',
        'line-width': 5
      }"
      [layout]="{
        'line-join': 'round',
        'line-cap': 'round'
      }"
    ></mgl-layer>
```

**Comment by clarke94** [comment]
@TheKeithStewart How do i get this data dynamically, it doesn't seem to work if the geometry routes are pulled in from a service after load? #218

**Comment by TheKeithStewart** [comment]
@clarke94 What you should be able to do is just create the `mgl-geojson-source` and `mgl-layer` components as you have the geometry for them. So, for the above example, wrap it in `<ng-container *ngIf="route">...</ng-container>`. This way the components are only instantiated if you have the data for them. I would think that you could also just use the async pipe to push the geometry into the components as you receive it.

**Comment by dmytro-gokun** [comment]
@vandres I guess your question has been answered, thus i'm closing this issue. If you still feel you need additional help here, feel free to comment and tell that.
