### ISSUE TITLE
Mapbox-gl supported versions

### ISSUE THREAD

**Issue by dimitrilahaye** [Wykks/ngx-mapbox-gl#213]
Hi!
Just need to know until which version of `mapbox-gl` can I use `ngx-mapbox-gl`?

**Comment by Wykks** [comment]
Hi, you can see this here:
Latest: 
https://github.com/Wykks/ngx-mapbox-gl/blob/master/projects/ngx-mapbox-gl/package.json#L25
V2.X : 
https://github.com/Wykks/ngx-mapbox-gl/blob/v2.x/projects/ngx-mapbox-gl/package.json#L25
V3.X : 
https://github.com/Wykks/ngx-mapbox-gl/blob/v3.x/projects/ngx-mapbox-gl/package.json#L25

**Comment by dimitrilahaye** [comment]
Thanks for the quick answer :)

So does it mean that if I'm using ngx-mapbox-gl on v 3.3.1 I should not use mapbox-gl on v 1.1.0?

**Comment by Wykks** [comment]
You shouldn't. But you can. I don't know if this works out of the box 🙃

**Comment by dimitrilahaye** [comment]
Ahah, I've just seen all the dependencies I need to upgrade, it will be funny :)
Thanks again!
