### ISSUE TITLE
Is there a way to add a search bar? 

### ISSUE THREAD

**Issue by jmm9683** [Wykks/ngx-mapbox-gl#217]
Trying to recreate this example https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/

And Id rather use npm packages in my angular app than the source code that they have.

**Comment by clarke94** [comment]
@jmm9683 you can add a searchbar with the mgl-control

```js
<mgl-map class="map" [style]="style" [zoom]="zoom" [center]="center">
    <mgl-control mglGeocoder></mgl-control>
</mgl-map>
```

Make sure you also add your geocoderAccessToken to your module imports

```js
NgxMapboxGLModule.withConfig({
     geocoderAccessToken: environment.MAP_KEY
 })
```

**Comment by timothyalcaide** [comment]
I think this issue is resolute ;)
