### ISSUE TITLE
mgl-layer not refreshing after data change

### ISSUE THREAD

**Issue by vandres** [Wykks/ngx-mapbox-gl#220]
I am having a simple setup, where I render a map, two marker and a route between these markers:

```
<mgl-map
    *ngIf="showUserData || community"
    [fitBounds]="showUserData | bounds: community"
    [fitBoundsOptions]="{padding: 100, maxZoom: 18}"
    [style]="'mapbox://styles/mapbox/streets-v9'"
>
    <ng-container *ngIf="route">
        <mgl-layer
            id="route"
            type="line"
            [source]="route | route"
            [paint]="{
            'line-color': '#FF3347',
            'line-width': 5
          }"
            [layout]="{
            'line-join': 'round',
            'line-cap': 'round'
          }"
        ></mgl-layer>
    </ng-container>

    <mgl-marker
        *ngIf="showUserData?.start"
        [lngLat]="[showUserData.start.geopoint.longitude, showUserData.start.geopoint.latitude]"
    >
    </mgl-marker>
    <mgl-marker
        *ngIf="showUserData?.goal"
        [lngLat]="[showUserData.goal.geopoint.longitude, showUserData.goal.geopoint.latitude]"
    >
    </mgl-marker>
</mgl-map>
```

This works pretty well for the first paint. But when I change the userData (onClick) and the  route, the map shows the new marker, the bounds change to the new position, but the route stays the same.

Am I doing something wrong?

Initial paint:
![Bildschirmfoto 2020-05-05 um 18 50 35](https://user-images.githubusercontent.com/1436383/81086656-780bcd00-8f01-11ea-9378-b98046ea527f.png)

After change:
![Bildschirmfoto 2020-05-05 um 18 51 26](https://user-images.githubusercontent.com/1436383/81086662-7b06bd80-8f01-11ea-9630-cc0d22e62fbc.png)

**Comment by vandres** [comment]
My route data looks something like that:

{"type":"geojson","data":{"type":"Feature","geometry":{"coordinates":[[7.024049,50.7985],[7.021852,50.796036],[7.023622,50.790512],[7.033419,50.780441],[7.027053,50.777851],[7.026403,50.776855],[7.021687,50.774815],[7.007402,50.769665],[6.999711,50.765915],[6.998404,50.76685],[6.996177,50.766808],[6.997006,50.763481],[6.997066,50.763332],[6.997271,50.762646],[6.997893,50.762779],[6.997978,50.762558]],"type":"LineString"}}}

**Comment by vandres** [comment]
For anyone interested, I found a workaround. I put the route into an array and generate a unique hash everytime the route changes. As far as I understand, the old component will get destroyed/destructed cleanly.

```
 <mgl-layer
            *ngFor="let route of routes, trackBy:trackByFn"
            [id]="route | hash"
            type="line"
            [source]="route | route"
            [paint]="{
                'line-color': '#4D7CFE',
                'line-width': 5
            }"
            [layout]="{
                'line-join': 'round',
                'line-cap': 'round'
            }"
        ></mgl-layer>
```

**Comment by vandres** [comment]
@dmytro-gokun Is there any resolution for this?

**Comment by dmytro-gokun** [comment]
@vandres Okay, i'm sorry for closing it. I thought you have found a way to make it work.
Anyways, could you provide a stackblitz that reproduces the issue using the latests versions of ngx-mapbox-gl & mapbox-gl?

**Comment by vandres** [comment]
I am not very familiar with Stackblitz. I'll try to explain the setup again, if it is still not clear, I can try myself with it.

- have a <mgl-layer> with a source with data binding
- the first time the layer renders with actual data, the drawing is fine
- now change the source, e.g. the user clicks on a button
- the layer is not redrawn

```
<mgl-map
    [fitBounds]="showUserData | bounds: community"
    [fitBoundsOptions]="{padding: 100, maxZoom: 18}"
    [style]="'mapbox://styles/mapbox/streets-v9'"
>
    <ng-container *ngIf="route">
        <mgl-layer
            id="route"
            type="line"
            [source]="route | route"
            [paint]="{
            'line-color': '#FF3347',
            'line-width': 5
          }"
            [layout]="{
            'line-join': 'round',
            'line-cap': 'round'
          }"
        ></mgl-layer>
    </ng-container>
</mgl-map>
```

**Comment by dmytro-gokun** [comment]
@vandres Here, i've creted a stackblitz using your code: https://stackblitz.com/edit/ngx-mapbox-gl-220
You can fork and edit it. First of all, it does not compile because of this custom pipes you are referencing: bounds & route. Plz make it compile and add a button to changes the source.

**Comment by vandres** [comment]
@dmytro-gokun Thank you very much! I made the changes: https://stackblitz.com/edit/ngx-mapbox-gl-220-3c2yo7

The second route should just be one line, but the layer doesn't redraw

**Comment by dmytro-gokun** [comment]
@vandres Great. I'll look at this shortly.

**Comment by dmytro-gokun** [comment]
@vandres So, the reason the map is not refreshing is that "source" property is "init only" as stated in the doc here: https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation#inputs-1

**Comment by dmytro-gokun** [comment]
@vandres Try creating a named source and change data there. That should work. See this answer: https://stackoverflow.com/a/63008662/7232025

**Comment by vandres** [comment]
Oh, ok. Then sorry for wasting your time. Thanks for the explanation!

**Comment by dmytro-gokun** [comment]
@vandres np
