### ISSUE TITLE
How to distinguish user-interaction and programmatic events? 

### ISSUE THREAD

**Issue by HighSoftWare96** [Wykks/ngx-mapbox-gl#223]
### mapbox-gl-js version:
1.9.1

### Question
I'm using the mapbox-gl-js package (specifically with this ngx-mapbox wrapper). I have an issue distinguishing the events that comes from the @Outputs that are triggered programmatically (in this case by changing the @Input) and the events triggered by a user interaction. Is there a way to know the difference between these two types of events without listening to all the user-interaction events possibile? I have not found anything neither in the documentation nor on StackOverflow.

In my particular case I'm listening to the moveend event and I the application loops when I try to save in the application state the map changes. Without distinguishing the event type I cannot really work around this issue....

**Comment by dmytro-gokun** [comment]
@HighSoftWare96 Most likely there is no way. May be you just do not need to save the app state if the new value coming in is not different from one already there. Something along this lines:

```
    private isCenterChanged(center: Location): boolean {
        if (this.map === undefined || this.map.mapInstance === undefined) {
            return true;
        }

        const currentCenter = this.map.mapInstance.getCenter();
        return center.latitude !== currentCenter.lat || center.longitude !== currentCenter.lng;
    }
```

P.S. If you want a better answer, plz provide a reproduction example. Stackblitz is the best way to do it.

**Comment by HighSoftWare96** [comment]
The problem was actually very similar. I think two-way binding the app state directly with the map input/output is just a bad idea.
