### ISSUE TITLE
Demo fails to work in edit mode

### ISSUE THREAD

**Issue by mojesto** [Wykks/ngx-mapbox-gl#227]
Clicking 'install' does not help

![mapbox](https://user-images.githubusercontent.com/6073086/85115286-1c34a380-b224-11ea-8f86-04cd093b0ed1.png)

**Comment by timothyalcaide** [comment]
You can clone this project https://github.com/Wykks/ngx-mapbox-gl/tree/master/projects/showcase 
if you don't know how to do it, i use svn for it. 

- Go on your project folder 
- svn checkout https://github.com/Wykks/ngx-mapbox-gl/trunk/projects/showcase
- npm i 
- npm start

**Comment by dmytro-gokun** [comment]
I've done some tweaking. Please let me know if it works for you or not. Remember to clear browser cache to make sure you are running the latest version of the demo site.

**Comment by dmytro-gokun** [comment]
It appears to be working fine now. I'll close this issue. If someone experiences this again - create a new issue
