### ISSUE TITLE
Satellite tiles 404 not forund when zoomed in

### ISSUE THREAD

**Issue by beshad** [Wykks/ngx-mapbox-gl#230]
i am having problem when using Satellite street view. map view becomes blurry with missing tiles and console errors

`VM1511:1 GET https://api.mapbox.com/v4/mapbox.satellite/17/129562/81256.webp?access_token=pk.eyJ1Ixxxg 404 (Not Found)` 

![image](https://user-images.githubusercontent.com/14914745/86552214-6eebba80-bf9b-11ea-88eb-e79b5164d8be.png)

the issue goes away when zoomed out, normally after zoom level 10 and i noticed this mostly exists on remote regions. is this an issue with MapBoxGL not having proper tile Ariel imagery or maybe i am doing something wrong?

![image](https://user-images.githubusercontent.com/14914745/86552416-0c46ee80-bf9c-11ea-9331-8cba6ebc3d59.png)

thanks

**Comment by dmytro-gokun** [comment]
I do not think this has anything to do with this library. Try the same area with a "pure" mapbox-gl-js sample and you, most probably, will see the same issue.

**Comment by beshad** [comment]
@dmytro-gokun you are right i just tried and i am having the same problem even when pure mapbox gl is used so nothing to do with this library.i will close the issue now. 

by any chance would you have any idea why this problem exists? is it because MapBoxGl doesn't have the right tiles for these areas cheers

**Comment by dmytro-gokun** [comment]
@beshad Sorry, I do not have an idea. Try asking on a mapbox-gl-js repo and/or StackOverflow.
