### ISSUE TITLE
[Question] Integration with Tileserver GL

### ISSUE THREAD

**Issue by Esteday** [Wykks/ngx-mapbox-gl#231]
For a personal learning project, I'm trying to implement Mapbox-GL, Angular and Tileserver GL but run into some issues. When I start the tileserver with the provided example data and try to hook up Mapbox it seems like it's not sending the ZYX coordinates. the console keeps logging 404 on the used url "http://localhost:8080/styles/basic-preview/{z}/{x}/{y}.png". When visited directly the tiles load as they should. 

By any chance, does someone have a quick example using nix Mapbox with tileserver?

**Comment by Terrafire123** [comment]
@Esteday Did you ever solve this?
