### ISSUE TITLE
Get the lineString feature when i click to it 

### ISSUE THREAD

**Issue by timothyalcaide** [Wykks/ngx-mapbox-gl#232]
I have a lineString, it represent a road on the map and i would like to select it and display it properties.

So i need to pass the feature when i click on the road, but i don't know how to do it. 

I was inspired by this example : https://stackblitz.com/edit/ngx-mapbox-gl-playground-x54fnd

When i click on a point i've got the feature (see in the console)

It's work with "ngx-mapbox-gl": "1.0.0-rc.3" but when i test it in my project coded with "ngx-mapbox-gl": "^4.6.0" it's doesn't work :/

So any idea ? :)

**Comment by timothyalcaide** [comment]
Please help me ! :)

**Comment by timothyalcaide** [comment]
Yes sorry not to be clear. 
You can find gifs, i hope it can help you to understand my issue : 
![gif](https://user-images.githubusercontent.com/17033036/87769677-43c85d00-c81e-11ea-8f3b-6fbb3cdf26d6.gif)
![gif2](https://user-images.githubusercontent.com/17033036/87769943-9f92e600-c81e-11ea-9b48-97f154038ab6.gif)

**Comment by dmytro-gokun** [comment]
@timothyalcaide 

1) You need to provide a minimal stackblitz which shows the problem. The stackbltz you provided does not do that + it uses ancient versions of the libs. I strongly advise to use the latest mapbox-gl-js & ngx-mapbox-gl;

2) If you look at recent mgl-layer's documentation here: https://github.com/Wykks/ngx-mapbox-gl/wiki/API-Documentation#mgl-layer-mapbox-gl-style-spec, you will see that (click) event has this shape: https://www.mapbox.com/mapbox-gl-js/api/#mapmouseevent. There are no "features" property.

3) If i understand your intent correctly here, you can find the feature(s) clicked by calling this function: https://docs.mapbox.com/mapbox-gl-js/api/map/#map#queryrenderedfeatures and the correct map.mapInstance object and passing lngLat from the event object passed to your click event and the name of the layer. To obtain the reference to map you can do something like this:

```
import { MapComponent } from 'ngx-mapbox-gl';

    @ViewChild('map')
    map: MapComponent;
```

**Comment by timothyalcaide** [comment]
@dmytro-gokun 
Property 'queryRenderedFeatures' does not exist on type 'MapComponent' from ngx-mapbox-gl. 
When i search on ngx-mapbox-gl i have queryRenderedFeatures on map.service.d.ts ... I don't understand anything anymore :/

**Comment by dmytro-gokun** [comment]
Sorry, i made typo in this phrase:

```
you can find the feature(s) clicked by calling this function: docs.mapbox.com/mapbox-gl-js/api/map/#map#queryrenderedfeatures and the correct map.mapInstance object and passing lngLat from the event object passed to your click event and the name of the layer
```

it should read:

```
you can find the feature(s) clicked by calling this function: docs.mapbox.com/mapbox-gl-js/api/map/#map#queryrenderedfeatures _on_ the correct map.mapInstance object and passing lngLat from the event object passed to your click event and the name of the layer
```

So, first, you obtain a reference to the map control using @ViewChild, then you call ```this.map.mapInstance.queryRenderedFeatures()```

**Comment by timothyalcaide** [comment]
Thank you very much @dmytro-gokun  !!! Now i have access to all function of mapbox-gl and i can have access to features !
