### ISSUE TITLE
Ability to find markers within a cluster using @Output event. This will be helpful for showing cluster points in a tooltip on cluster.

### ISSUE THREAD

**Issue by ShubhamJainSJ** [Wykks/ngx-mapbox-gl#235]

**Comment by dmytro-gokun** [comment]
@ShubhamJainSJ Plz elaborate. At least provide an example of code how would you like it to be vs how it is today.

**Comment by ShubhamJainSJ** [comment]
@dmytro-gokun I did some more research on it and found that the feature I requested can be achieved by `getClusterLeaves()` function
`let leaves: GeoJSON.Feature<GeoJSON.Geometry>[] = await this.clusterComponent.getClusterLeaves(selectedCluster.properties!.cluster_id, 50, 0);`

I will close this issue as the feature is already supported. Thanks for your reply.
