### ISSUE TITLE
Dynamically adding geojson points in click?

### ISSUE THREAD

**Issue by jamesrusso** [Wykks/ngx-mapbox-gl#242]
I am working on an application where I need to click on various areas in a map and then look up that location in a database and then add the circle to the map in the lat/long returned by the database. I am adding the points to the underlying geojson data, but they are never appearing unless they are loaded in ngOnInit?

Is there a way to dynamically add a Feature (point) to a FeatureCollection in the click method?

I feel that it's some type of javascript/angular boundary issue?

thanks!

-jr

**Comment by dmytro-gokun** [comment]
@jamesrusso Check out this sample: https://wykks.github.io/ngx-mapbox-gl/demo/live-update-feature. It is not exactly what you need, but it will give you an idea.

**Comment by jamesrusso** [comment]
@dmytro-gokun Thanks for your help. 

Here is a stackblitz based on your example that shows what I am trying to do? I am adding to the FeatureCollection in the click, but it is ever reflected in the map? Where you click should add a point to the map. 

https://stackblitz.com/edit/angular-ghftly?file=src/demo.ts

**Comment by dmytro-gokun** [comment]
@dmytro-gokun You missed this line in the example:

```
this.data = { ...this.data };
```

This creates a new object reference, so Angular knows there was a change and renders properly. May be there is a more elegant way to achieve this (ngDoCheck?), but i cannot think about it right away.

**Comment by jamesrusso** [comment]
Thanks! I'll try it out and report back. Appreciate the help again!

**Comment by jamesrusso** [comment]
Working now! Thanks again for your help!
