### ISSUE TITLE
Adding promoteId as input for mgl-vector-source and mgl-geojson-source

### ISSUE THREAD

**Issue by magnolo** [Wykks/ngx-mapbox-gl#245]
Hello there, i am so blessed and thankful for your work and effort for this lib. I am using it very intense and its great.
I am following a lot of your issues and sometimes i whish i had time to contribute to it and help out a bit. Maybe soon...

My issue here is, that i would like to use a promoteId input for mainly mgl-vector-source so i could use setFeatureState for some of my user interactions and data changes. Would it be possible to integrate it in near future?

I think this wouldnt be a big update and no breaking change. (but just thinking, not knowing)

love M

**Comment by ezk84** [comment]
This was fixed with #253, AFAIK?

**Comment by dmytro-gokun** [comment]
@ezk84 Yes, it was.
