### ISSUE TITLE
Expose `maxPitch` and `minPitch` on mgl-map

### ISSUE THREAD

**Issue by StephaneAlie** [Wykks/ngx-mapbox-gl#247]
I'd like to start by saying great library, very robust, thank you!!

I noticed missing inputs `maxPitch` and `minPitch` on mgl-map (see [mapbox-gl-js doc](https://docs.mapbox.com/mapbox-gl-js/api/map/#map-parameters).) I should have a PR shortly for it if you'll allow it.

Cheers

**Comment by dmytro-gokun** [comment]
@StephaneAlie PRs are welcome. I will review as soon as I can.

**Comment by Wykks** [comment]
Fixed with https://github.com/Wykks/ngx-mapbox-gl/pull/253
