### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by dmytro-gokun** [Wykks/ngx-mapbox-gl#249]
According to an e-mail i've got from travis CI (https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=5960f11630), travis-ci.org is going to be closed on December 31, 2020, thus:

```
We encourage you to migrate your existing repositories that are currently on travis-ci.org over to travis-ci.com as soon as possible, enabling you to identify any additional changes required to your code or configuration well in advance of the December 31st deadline.
```

@Wykks Do you mind migrating it? Looks like it's pretty straightforward process (https://docs.travis-ci.com/user/migrate/open-source-repository-migration).

**Comment by Wykks** [comment]
I was thinking about migrating to github actions, since it's a thing now.
I'll look into it someday :)

**Comment by dmytro-gokun** [comment]
@Wykks You are absolutely right. But who knows when that day comes. And travis-ci.org has only 3 more months to leave and the migration is really easy ... ;)

**Comment by Wykks** [comment]
Done :)

**Comment by dmytro-gokun** [comment]
Hoorray, thanks! 
Though, it looks like we have some Markup funkiness in README.md:

![image](https://user-images.githubusercontent.com/580460/94369993-b5ae0400-00f5-11eb-8b10-daa07aec9bda.png)

**Comment by Wykks** [comment]
whoops, fixed 😅
