### ISSUE TITLE
Change Detection Issue with Map

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [Wykks/ngx-mapbox-gl#25]
I've tried to add ngx-mapbox-gl to a couple of projects of mine but I'm stuck on Change Detection Issues. It's been very difficult to debug cause I'm not getting any error messages in the console.

I've created a [Stackblitz](https://stackblitz.com/edit/mgl-project) to demonstrate some areas of confusion.  Basically, this app just toggle's an Angular Material Side-navigation component in and out on click. Different click events for the boilerplate on top and the mgl-map on the bottom.

My first question relates to line: 58 in `app.component.ts` Why do I need to detect for changes using Angular's ChangeDetectionRef in order for the sidenav to open and close?

**Comment by Wykks** [comment]
Hi!

Why do you use `fromEvent<MapMouseEvent | MapTouchEvent>(mglMap, 'click')` while you can bind click event from the template ?

In your code, the reason why you need to call `detectChanges` is because `ngx-mapbox-gl` run `mapbox-gl` outside the angular zone for performance reason.

When using the `click` output from `ngx-mapbox-gl` it's properly run inside the angular zone: https://github.com/Wykks/ngx-mapbox-gl/blob/fdfc7461f1db65a7d04baba593d87b49446a5a61/src/app/lib/map/map.service.ts#L452

I probably should add this information in the doc :upside_down_face:

**Comment by wheredoesyourmindgo** [comment]
Ah. I see. I wonder what my best course of action would be. I'd like to use the mapbox map's functionality outside of the component that is hosting the `<ngx-mapbox-gl/>` component, such as in a separate service.  I'd also like to use rxjs with the map as well.  Can you think of the best work around?  Certainly in the trivial example I provided above it would be just as easy to use the ngx-mapbox-gl click (output) property to trigger the sidenav toggle.
Now that I understand what is happening, one workaround I'm considering at this point is to use ngrx, or a separate Angular Service combined w/ BehaviorSubjects to store all events emitted by the ngx-mapbox-gl component using their corresponding output events, and dispatching to the store the event each time that happens. That way the events can be accessed in a separate service.  I think this is sort of discussed in #19 .  Any feedback is appreciated. I'll close this since it's not an issue.  Great work btw, thanks for sharing 👍

**Comment by Wykks** [comment]
What you're saying is valid for every component where you need to "broadcast" their event (output) elsewhere than in the host component. It's a classic concern, unrelated to `ngx-mapbox-gl` (but i'll admit that it's much more common with `ngx-mapbox-gl` given the number of outputs). Having access to the Map object is a "bonus", and should be used when you need to do something not supported by `ngx-mapbox-gl`.

You can just pass up the outputs, create a service or use advanced state management (ngrx / mobx / ...) as you said :+1: 
I planned to create an app with `ngrx` and `ngx-mapbox-gl`, someday :)
