### ISSUE TITLE
angular 10 error 'mgl-map' is not a known element:

### ISSUE THREAD

**Issue by passionashley** [Wykks/ngx-mapbox-gl#251]
angular 10 error 'mgl-map' is not a known element: - 
How to fix the error

**Comment by dmytro-gokun** [comment]
Please use stackoverflow for questions like this one.

**Comment by jpike88** [comment]
I'm having this issue too, and only with this library, none other. There is something weird about how this particular library is formed and needs attention from the maintainer.
