### ISSUE TITLE
Problem importing NgxMapboxGLModule

### ISSUE THREAD

**Issue by rhegner** [Wykks/ngx-mapbox-gl#254]
I'm trying to add ngx-mapbox-gl to an existing Angular 10 (v10.2.2) application.
When adding `NgxMapboxGLModule` to the imports of my `AppModule`, I get the following error message:

```
PS > ng build   

ERROR in node_modules/ngx-mapbox-gl/lib/ngx-mapbox-gl.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-mapbox-gl/lib/ngx-mapbox-gl.module) which declares NgxMapboxGLModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2 export declare class NgxMapboxGLModule {
                       ~~~~~~~~~~~~~~~~~
```

Is this a known issue? How can I fix it?

I'm using:
```
"mapbox-gl": "1.12.0",
"ngx-mapbox-gl": "4.8.1",
"@types/mapbox-gl": "1.12.5"      (in `devDependencies`)
```

**Comment by IKondor** [comment]
It's all about Ivy
I have this problem too and solve is: set `"enableIvy": false` on `angularCompilerOptions` in `tsconfig.lib.json`
[this file](https://github.com/Wykks/ngx-mapbox-gl/blob/master/projects/ngx-mapbox-gl/tsconfig.lib.json)

**Comment by dmytro-gokun** [comment]
@rhegner Do you still have this issue? If yes, please post a minimal reproduction sample (via stackblitz or a separate repo). If no - how did you fix it?

**Comment by rhegner** [comment]
I ended up using Mapbox directly (without using this angular wrapper).
