### ISSUE TITLE
The default configuration does not work

### ISSUE THREAD

**Issue by rudyhadoux** [Wykks/ngx-mapbox-gl#255]
Hi,

The default configuration in the read.me does not work with :

@Component({
  template: ` <mgl-map [style]="'mapbox://styles/mapbox/streets-v9'" [zoom]="[9]" [center]="[-74.5, 40]"> </mgl-map> `,
  styles: [
    `
      mgl-map {
        height: 100%;
        width: 100%;
      }
    `,
  ],
})
export class DisplayMapComponent {}

mgl-map { height: 100%; width: 100%; } is 100% of a parent div. Without a parent div with dimensions it is invisible. it's a bit confusing without this important detail.

**Comment by Wykks** [comment]
Hi!

What would you recommend instead ?

**Comment by rudyhadoux** [comment]
You just have to add a parent div in template like that :
<div style="width:90vw;height:90vh;"></div>
