### ISSUE TITLE
transformRequest context

### ISSUE THREAD

**Issue by denaillc** [Wykks/ngx-mapbox-gl#259]
Hi,

I am migrating a map from vanilla js to an Angular project using ngx-mapbox-gl.
I cannot seem to find how to use a variable in the function that is passed as the transformRequest : 
```html
<mgl-map [style]="style" [zoom]="[9]" [center]="center" [transformRequest]="injectToken"></mgl-map>
```

```typescript
injectToken(url: string, resourceType: ResourceType): RequestParameters {
      if (
        resourceType === 'Tile' &&
        url.startsWith('my-url')
      ) {
        if (this.authToken !== undefined) {
          return {
            url,
            headers: {
              Authorization: this.authToken,
            },
          };
        } else {
          throw new Error(`authToken is ${this.authToken}`);
        }
      }
  }
```

I tried with NgZone too :

```typescript
injectToken(url: string, resourceType: ResourceType): RequestParameters {
    return this.zone.run(() => {
      console.log(this.style);
      console.log(this.authToken, url);
      if (
        resourceType === 'Tile' &&
        url.startsWith('my-url')
      ) {
        if (this.authToken !== undefined) {
          return {
            url,
            headers: {
              Authorization: this.authToken,
            },
          };
        } else {
          throw new Error(`authToken is ${this.authToken}`);
        }
      }
    });
  }
```

I am trying to inject a JWT in the tile requests headers, but cannot access my auth service, or any variable set in the Angular component. Did I miss something ?

**Comment by dmytro-gokun** [comment]
@denaillc "injectToken" is going to be called from within mapbox-gl itself which has no clue about your Angular object and would not call your function with correct "this" value. So, for this to work, you need to bind "this" to your "injectToken" function.

**Comment by dmytro-gokun** [comment]
@denaillc I'm closing this as it has nothing to do with this library. Please use StackOverflow to ask questions.

**Comment by 0nza1101** [comment]
Since binding in the template like so : `<mgl-map [style]="style" [zoom]="[9]" [center]="center" [transformRequest]="injectToken.bind(this)"></mgl-map>` won't work for me (browser stuck).
This worked :
`<mgl-map [style]="style" [zoom]="[9]" [center]="center" [transformRequest]="injectToken"></mgl-map>`
`injectToken = (url: string, resourceType: ResourceType): RequestParameters => {
      if (
        resourceType === 'Tile' &&
        url.startsWith('my-url')
      ) {
        if (this.authToken !== undefined) {
          return {
            url,
            headers: {
              Authorization: this.authToken,
            },
          };
        } else {
          throw new Error(`authToken is ${this.authToken}`);
        }
      }
  }`
More details on whats going on behind can be found [here](https://lukeliutingchun.medium.com/angular-why-you-should-and-how-to-avoid-function-prototype-bind-in-template-c9b712423d52)
