### ISSUE TITLE
Mapbox transition out of open source world

### ISSUE THREAD

**Issue by HarelM** [Wykks/ngx-mapbox-gl#260]
It seems that Mapbox is transitioning out of free open source license.
There's a project now forming around the open source port of this:
https://github.com/maplibre
It might be nice to have this project there and reference the open source version of mapbox (maplibre).
Another option is to allow dependencies of one of the projects - maplibre and mapbox and avoid warning in NPM when installing it.

**Comment by dmytro-gokun** [comment]
@HarelM What do you mean they are "transitioning out of free open source license"? I do not see anything in their new license agreement which would point me towards that conclusion. Granted, it is not BSD anymore, but it is still free to use for everyone. Am I wrong? Could you please elaborate?

**Comment by HarelM** [comment]
The internet is full of articles ranting about it :-)
Here's one:
https://l.facebook.com/l.php?u=https%3A%2F%2Fjoemorrison.medium.com%2Fdeath-of-an-open-source-business-model-62bc227a7e9b%3Ffbclid%3DIwAR0xqxrtHNtdfjdDBIdwLeELHCWgcB3iUbXRuwl3gXtpCb6touqCkjW7wgI&h=AT2nElHI_d--_JLkhcpuhqFJkuBKI6a6U14LAVjEmg0-MczGQqHIpALRHwwPv-RVUKJVnqlnFUHwvWMTiEP_bbYVdbrGO-Ap-qzmX54x5nb9GdyeMJzbsRjIJsIMD_KRd2Ae&__tn__=H-R&c[0]=AT1HlayPEWvI41_gJ4GwV4dB4_qpMcBwVoEBotGI_29YEMR9ah0NlcrgH4FYmyVT1Jcz6Z2_IZmssgevJgscRr4BuHWXFoHZF98V9drf4m57nikM335pdVBhKGEjfFDOmSpr0D4KtOijOkr5XjzQgikz5UAo9TR69DbcFKA_I-RwW-w8XLdTmKHqjbqewZ67R3ZojK1s9Cv7Bk-I-Q
In version 2. you have to have a mapbox token to use the library.
I haven't created one up until now and won't be able to use the new version for that reason.
I'm not sure this library is affected by this change as you would need to get a token regardless of this library and use mapbox anyway, but I think it's worth considering which library should be the default "under the hood".
In any case, I've posted a comment about it in the new repository and though that this "github company" might be a good place to host this repository if and after it uses the new library.

**Comment by dmytro-gokun** [comment]
> In version 2. you have to have a mapbox token to use the library.

Can you point our a clause in their license which makes you think so?

**Comment by HarelM** [comment]
"Developers may modify the
Mapbox Web SDK code so long as the modifications do not change or interfere with
marked portions of the code related to billing, accounting, and anonymized data
collection".
I might be wrong though. Don't take my word for it... :-)

**Comment by dmytro-gokun** [comment]
Well, what this clause says is that you cannot modify particular part of SDK. It does not say anything about using SDK without a mapbox token. That's how I understand it. I've read this yesterday and did not see anything particularly spooky for the library users :) I might be wrong here though.

**Comment by magnolo** [comment]
Its not totally clear to me because i have not tried yet, but mapbox 2.0 seems to require a token to initialize. Am i wrong here?

**Comment by dmytro-gokun** [comment]
What i can find so far here https://www.mapbox.com/legal/tos/:

"When you use our application program interfaces (APIs), including our SDK Registry/Downloads API, each request to an API must include one of your account's unique API keys."

So, indeed 2.0.0 will only work with mapbox's API keys. We'll see what this really means in the future.
Still, version 1.1.13 remains as is forever. Granted, it will not get any updates, but it is good enough as is.

What @HarelM suggests makes sense. Though, i'm not sure if it's a good idea to have this wrapper work with both mapbox >= 2.0.0 and some other OSS fork. Over time they will diverge and support will become a nightmare. So, my gut reflex would be to fork this lib to use with any OSS alternatives out there. Let's not make any rush decisions though :)

**Comment by HarelM** [comment]
No problem, just wanted to start a discussion and let you guys know of the recent news :-)
Keep up the good work!

**Comment by Wykks** [comment]
Thanks for the head up. I saw the 2.0.0 release briefly but didn't noticed this big licensing change.

Let's wait and see for now...

**Comment by almothafar** [comment]
It seems 2020 don't want to end with good news lol
Even Kendo now requires a license to work! https://www.telerik.com/kendo-angular-ui/my-license/ 

Every company now wants to get money in any way!

It seems good days are no more.

**Comment by dmytro-gokun** [comment]
@Wykks I think this is not much to do here. If someone wants to fork this repo and start supporting maplibre, that's okay. But I highly doubt this library will support it. Maybe we should just close this issue.

**Comment by HarelM** [comment]
I don't mind forking and helping maintain the maplibre fork but I was hoping you guys would join me there... If this is not the direction you would like to pursue that totally fine! I mainly wanted to know where you stand.
I truly appreciate all the hard work invested in this amazing wrapper! Keep it up.

**Comment by dmytro-gokun** [comment]
@HarelM IMO, the libs will inevitably diverge and maintaining single wrapper for both will become harder and harder (error-prone and so on). That being said, if it some point our company decides to switch to maplibre, I will definitely come to help with a wrapper for it.

**Comment by HarelM** [comment]
Fair enough. My initial assumption is that there won't be a single wrapper, but rather two wrappers each for each library - as I agree that maintaining a single wrapper for both will become harder or not possible over time.
I'll fork this one to maplibre github company and let you guys know how it goes... I still need something implemented in mablibre before I can switch to it, I hope it will happen soon.

**Comment by dmytro-gokun** [comment]
Closing the issue for now. Let's re-visit this when (if) the need arises

**Comment by HarelM** [comment]
For anyone reading this in the future, I've started a fork to support maplibre here:
https://github.com/maplibre/ngx-maplibre-gl
It's still in very early stages right now but I hope to spin up a npm package soon.
Feel free to join me there.
I would like to personally thank all the @maintainers of this awesome project. It's truly a fine piece of software. If the credit I added in my fork is not enough or you would like me to add anything else please let me know.
I would like to emphasize that I have nothing but respect to the people who work on this wrapper which I used for a long time and served me extremely well.
