### ISSUE TITLE
Angular 11 : Module '"../../../@types/mapbox-gl"' has no exported member 'Alignment'

### ISSUE THREAD

**Issue by constantlb** [Wykks/ngx-mapbox-gl#264]
These two errors appear with Angular 11 project : 

> Error: node_modules/ngx-mapbox-gl/lib/map/map.service.d.ts:5:10 - error TS2305: Module '"../../../@types/mapbox-gl"' has no exported member 'Alignment'.
> 
> 5 import { Alignment } from 'mapbox-gl';
>            ~~~~~~~~~
> node_modules/ngx-mapbox-gl/lib/marker/marker.component.d.ts:2:49 - error TS2305: Module '"../../../@types/mapbox-gl"' has no exported member 'Alignment'.
> 
> 2 import { LngLatLike, Marker, PointLike, Anchor, Alignment } from 'mapbox-gl';

With the last version of this two modules : 

    "mapbox-gl": "^1.13.0",
    "ngx-mapbox-gl": "^4.8.1",
___

It's works on angular 11 with these version for me : 

    "mapbox-gl": "1.10.0",
    "ngx-mapbox-gl": "4.5.0",

**Comment by dmytro-gokun** [comment]
@constantlb Does the problem exist with the latest versions of all three libs (mapbox-gl, ngx-mapbox-gl, @types/mapbox-gl)?

**Comment by happyxhw** [comment]
> @constantlb Does the problem exist with the latest versions of all three libs (mapbox-gl, ngx-mapbox-gl, @types/mapbox-gl)?

same problem with 6.0.4 & angular11

**Comment by dmytro-gokun** [comment]
@happyxhw That's interesting. Would you mind creating a small reproduction project (or stackblitz)?

**Comment by happyxhw** [comment]
> @happyxhw That's interesting. Would you mind creating a small reproduction project (or stackblitz)?

Thank you for you reply, I had fixed this problem with runing:

```shell
npm install --save @types/geojson
```

**Comment by dmytro-gokun** [comment]
@happyxhw Great!
