### ISSUE TITLE
Image source is not working in Firefox and Safari

### ISSUE THREAD

**Issue by danijelcigula** [Wykks/ngx-mapbox-gl#266]
Hi, the ["Update an image source in realtime"](https://wykks.github.io/ngx-mapbox-gl/demo/live-update-image-source) is not working in Firefox and Safari.

**Comment by dmytro-gokun** [comment]
@danijelcigula Did you make it work or? Please share your solution if there is any.

**Comment by danijelcigula** [comment]
@dmytro-gokun I close this because is the same as this - #267
