### ISSUE TITLE
The image source is not working in Firefox and Safari

### ISSUE THREAD

**Issue by danijelcigula** [Wykks/ngx-mapbox-gl#267]
Hi, the [Update an image source in realtime](https://wykks.github.io/ngx-mapbox-gl/demo/live-update-image-source) is not working in Firefox and Safari.

**Comment by dmytro-gokun** [comment]
@dmytro-gokun Could you plz elaborate? I've checked and it seem to work for me. Please provide us much info as you can. OS version, browser version. A screen recording would be of a great help.

**Comment by danijelcigula** [comment]
@dmytro-gokun It looks like it works now. To reproduce you simple opened [link](https://wykks.github.io/ngx-mapbox-gl/demo/live-update-image-source) in safari (there was no moving image). But not is workin. I'm closing this issue.
