### ISSUE TITLE
Support Angular 11

### ISSUE THREAD

**Issue by HarelM** [Wykks/ngx-mapbox-gl#268]
I'm guessing that this package already support this, but I would consider changing the major and minor version to match those of Angular to let the users know which version of this library is compatible to which Angular version...
This is just a suggestion from other packages I've seen to do the same.
The main requirement here is that the warning when using npm install will be gone :-)

**Comment by tillkuhn** [comment]
Same here. I recently switched to Angular 11 and while I have not faced any issues with Mapbox related code so far, the build warnings are a bit annoying. Thanks!

```
warning " > ngx-mapbox-gl@5.0.0" has incorrect peer dependency "@angular/common@>= 8.0.0 < 11.0.0".
warning " > ngx-mapbox-gl@5.0.0" has incorrect peer dependency "@angular/core@>= 8.0.0 < 11.0.0".
```

**Comment by Wykks** [comment]
Done in https://github.com/Wykks/ngx-mapbox-gl/pull/273 (thanks @Nosfit  :) )
