### ISSUE TITLE
[v6.0.2] Missing interface GeolocationCoordinates 

### ISSUE THREAD

**Issue by eschricker** [Wykks/ngx-mapbox-gl#277]
I have updated ngx-mapbox-gl to 6.0.2. When building my angular project I get the following error: 

```
Error: node_modules/ngx-mapbox-gl/lib/map/map.types.d.ts:119:13 - error TS2304: Cannot find name 'GeolocationCoordinates'.

119     coords: GeolocationCoordinates;
```

With 6.0.1 its working.

**Comment by dmytro-gokun** [comment]
@eschricker Please check out 6.0.3

**Comment by eschricker** [comment]
Now it's working! Thanks for the quick response :)
