### ISSUE TITLE
Reference error after updating to 2.0 version

### ISSUE THREAD

**Issue by Wonnder22** [Wykks/ngx-mapbox-gl#279]
I recently updated to Angular 11 and your Mapbox 2.0 version and since then Im getting this error.
![image](https://user-images.githubusercontent.com/78858950/107516149-44ef1c00-6bac-11eb-913d-1bf5da163316.png)

The app compiles without errors but you can only see a div with beige background in the preview, I think its a common issue after jumping to version 2.0 of Mapbox,as many React users have reported this, but I have never seen a fix of this bug for Angular.
![image](https://user-images.githubusercontent.com/78858950/107516560-dfe7f600-6bac-11eb-8932-497fa3bf2d3d.png)

**Comment by dmytro-gokun** [comment]
Please provide a stackblitz with a reproduction

**Comment by vandres** [comment]
Get the same error. After mangeling it is "ReferenceError: y is not defined". I am only getting it, after a production AoT build. In development it doesn't occur.

It seems to be related to this issue opened in the mapbox-gl-js repository. They also meantion a workaround, but I have no idea how to apply it https://github.com/mapbox/mapbox-gl-js/issues/10173#issuecomment-788940677

**Comment by vandres** [comment]
I have one more insight. When I switch my build to ES2015 (`"target": "es2015",`), that error doesn't occur. It only occurs for ES5 builds.

**Comment by dmytro-gokun** [comment]
@Wonnder22 Please check out if this problem still exists with the latest version (7.0.0) and if it does open a new issue
