### ISSUE TITLE
force resize?

### ISSUE THREAD

**Issue by makdeniss** [Wykks/ngx-mapbox-gl#282]
Hey,

How can I force a resize of map after a certain operation? I need this for an ionic as this one has troubles with inner element height?

**Comment by bashasm** [comment]
have you used `map.resize();` on the actual map instance

**Comment by shuabrannigan** [comment]
ran into a similar issue when running ionic app on iOS, seemed to be when the keyboard popped up the map would never go back to fullscreen. 

solution we are using currently is to emit an event when we know the interaction with the keyboard is finished and run `map.resize();` on the map instance.
