### ISSUE TITLE
Mapbox GL new license

### ISSUE THREAD

**Issue by long3009** [Wykks/ngx-mapbox-gl#283]
Dear all,
Mapbox gl is not free, now. Do you have any plan to support "maplibre-gl"? Please refer to this news https://www.maptiler.com/news/2021/01/mapbox-gl-open-source-fork/
Thanks

**Comment by dmytro-gokun** [comment]
https://github.com/Wykks/ngx-mapbox-gl/issues/260

**Comment by long3009** [comment]
Thanks

**Comment by HarelM** [comment]
@long3009 I have created a fork (see my last comment in the linked issue), I still need to make it work with maplibre, you are welcome to join in the effort.
