### ISSUE TITLE
Error importing NgxMapboxGLModule

### ISSUE THREAD

**Issue by 0xF76** [Wykks/ngx-mapbox-gl#284]
### Hey there!
I'm trying to import **NgxMapboxGLModule**
```js
import { NgxMapboxGLModule } from 'ngx-mapbox-gl';
```
And i get an error

```node
Error: node_modules/ngx-mapbox-gl/lib/control/geocoder-control.directive.d.ts:2:8 - error TS1259: Module '"<path>"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

2 import MapboxGeocoder, { Result, LngLatLiteral } from '@mapbox/mapbox-gl-geocoder';       
         ~~~~~~~~~~~~~~

  node_modules/@types/mapbox__mapbox-gl-geocoder/index.d.ts:10:1
    10 export = MapboxGeocoder;
       ~~~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```
I've added `allowSyntheticDefaultImports` and `esModuleInterop` flags to `tslint.json` but it still doesn't work.

Has anyone had this problem and can help me?

**Comment by dc480506** [comment]
What was the workaround for this because I'm also getting this error.

**Comment by 0xF76** [comment]
> 
> 
> @0xF76 What was the workaround for this because I'm also getting this error

I changed 
`import { NgxMapboxGLModule } from 'ngx-mapbox-gl';`
to
`import * as MapboxGl from 'mapbox-gl';`
in
`node_modules/ngx-mapbox-gl/__ivy_ngcc__/fesm2015/ngx-mapbox-gl.js`

**Comment by dc480506** [comment]
@0xF76 In my file i.e. node_modules/ngx-mapbox-gl/__ivy_ngcc__/fesm2015/ngx-mapbox-gl.js , the import statement is already correct.
