### ISSUE TITLE
MapboxGL 2.1.1 cannot run without token

### ISSUE THREAD

**Issue by andrewaldasoro** [Wykks/ngx-mapbox-gl#286]
MapboxGL 2.1.1 is not accepting null tokens anymore 😢
https://stackblitz.com/edit/ngx-mapbox-gl-without-token-y2hjdf

### README.md:98 -> Line should be deleted. or Find a workaround,
(Note: `mapbox-gl` can work without a token, if you have your own source, for example: https://stackblitz.com/edit/ngx-mapbox-gl-without-token)

I tried with an updated project without token and it didn't work.

![image](https://user-images.githubusercontent.com/31018159/109847384-20231d00-7c1d-11eb-85c5-3bf9090afee8.png)

**Comment by DroidZed** [comment]
Check #287 , I've done the pull request for the fix to be taken care of.

**Comment by dmytro-gokun** [comment]
Thanks for the PR, @DroidZed! I've merged it in, readme is updated.

**Comment by DroidZed** [comment]
You're welcome !
