### ISSUE TITLE
Support Angular 12

### ISSUE THREAD

**Issue by airbreather** [Wykks/ngx-mapbox-gl#298]
Like #268, but with the version number incremented by 1

**Comment by dmytro-gokun** [comment]
@airbreather PR is welcome :)

**Comment by Carniatto** [comment]
@dmytro-gokun can you check my PR?

**Comment by dmytro-gokun** [comment]
@Carniatto Thanks for the PR. Unfortunately, we cannot use this directly as we've already started working on lib split (will be pushed shortly), but we will use your ideas to update to Angular 12 later this week,

**Comment by Carniatto** [comment]
@dmytro-gokun thanks, This is blocking our update to Angular 12 and Nx 12.3 is quite critical

**Comment by dmytro-gokun** [comment]
The new version of the library with Angular 12 support has been released: https://www.npmjs.com/package/ngx-mapbox-gl/v/7.0.0

Please try that out and if something does not work as expected feel free to open new issues in this repository.
