### ISSUE TITLE
Provide example for using mgl-layer

### ISSUE THREAD

**Issue by visurel** [Wykks/ngx-mapbox-gl#30]
On the API documentation for the `mgl-marker` component you write: 

> Note: Only use this if you really need to use HTML/Angular component to render your symbol. These markers are slow compared to a Layer of symbol because they're not rendered using WebGL.

Could you provide an example on how to accomplish this and maybe how to attach a popup to a marker created like this?

Thanks a lot for this library!

**Comment by visurel** [comment]
Thanks for the quick response!
As far as I can see it's not possible to add a layer and later on update the features, they can only be added on init, is there any reason to that?

**Comment by visurel** [comment]
Thanks a lot! Really appreciate the examples! 👍

**Comment by apptum** [comment]
@Wykks just to be sure and for everyone else landing here in the future: using an observable on `data` input of `mgl-geojson-source` via async pipe, that ist like this
```
  <mgl-geojson-source
    id="'points-source'"
    [data]="data$ | async"
  >
  </mgl-geojson-source>
```
should be fine, or miss I something?

**Comment by Wykks** [comment]
If `data$` emit a new ref each time (which is often the case), then yes :)
