### ISSUE TITLE
fullscreen is not working in safari

### ISSUE THREAD

**Issue by sarath-k** [Wykks/ngx-mapbox-gl#301]
In full screen view with safari, it si showing a small area map and rest of the space are blank. Kindly help to resolve the issue
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/85979900/122158416-41d1a880-ce8a-11eb-826d-c24807f99423.png)

https://wykks.github.io/ngx-mapbox-gl/demo/fullscreen, this demo also not working properly in safari

**Comment by sarath-k** [comment]
@Wykks

**Comment by dmytro-gokun** [comment]
@sarath-k Is this of any help: https://github.com/mapbox/mapbox-gl-js/issues/7990 ?

**Comment by sarath-k** [comment]
@dmytro-gokun the below code helped me to fix the issue.

**component.ts**

@HostListener('webkitfullscreenchange', ['$event'])
screenChange() {
  this.map.resize();
}

**component.html**
   <mgl-map
    [style]="'mapbox://styles/mapbox/streets-v11'"
    [zoom]="[5]"
    [center]="[77.3453388, 12.782237]"
    (mapLoad)="map=$event"
  >

**Comment by dmytro-gokun** [comment]
@sarath-k Glad you've found the solution. And thank for sharing it!
