### ISSUE TITLE
Mapbox GL CSS missing

### ISSUE THREAD

**Issue by rohanrichards** [Wykks/ngx-mapbox-gl#31]
I was having an issue where the css was giving a 404, I was importing it as per the instructions:
`@import "~mapbox-gl/dist/mapbox-gl.css";`
The fix was to remove the `.css` from the end of the import statement. 
`@import "~mapbox-gl/dist/mapbox-gl";`
I'm not sure if this is implementation specific (I am using  [Angular full-stack generator](https://github.com/angular-fullstack/generator-angular-fullstack) ), which uses SCSS/webpack/angular5. Or if this is simply an error in your documentation.

**Comment by Wykks** [comment]
Hi!

The readme state "For example, with **angular-cli**". Of course depending on your setup, the way you include a global css file may be different than the way it's done with angular-cli :)
