### ISSUE TITLE
Popup autofocus

### ISSUE THREAD

**Issue by neverwalk** [Wykks/ngx-mapbox-gl#324]
Hi team,
I'm having trouble with auto-focusing the popup when the map is being initialized. And the main reason is the default value of attribute "focusAfterOpen" is true [(https://docs.mapbox.com/mapbox-gl-js/api/markers/#popup)](https://docs.mapbox.com/mapbox-gl-js/api/markers/#popup)
Can you help me add more input attributes ("focusAfterOpen", "closeOnMove") to the "mgl-popup" component? We are creating a popup without their attributes (`ngx-mapbox-gl/src/lib/popup/popup.component.ts line 122`)

Thanks,

**Comment by dmytro-gokun** [comment]
@neverwalk A PR is welcome :)

**Comment by dmytro-gokun** [comment]
Closed vis #325
