### ISSUE TITLE
Angular 12 [cross] failed to load response

### ISSUE THREAD

**Issue by SalahAbasMo** [Wykks/ngx-mapbox-gl#336]
i already implemented the map like the documentation and the map failed to load some request an loaded others 

here is the problem : ( at api request "https://events.mapbox.com/events/v2")

![image](https://user-images.githubusercontent.com/30913782/136705928-98cf1f56-a4a9-41e3-8e11-1cff502be1d8.png)

![image](https://user-images.githubusercontent.com/30913782/136706034-3c4f83f7-3aa0-43d6-88a2-f12229c77210.png)

**Comment by cyberbobjr** [comment]
Hi,
I have the same problem, how do you fix it please ?
