### ISSUE TITLE
Upgrade to angular 6 and rxjs 6

### ISSUE THREAD

**Issue by ciukstar** [Wykks/ngx-mapbox-gl#34]
After upgrade to angular 6:
**ERROR in node_modules/ngx-mapbox-gl/app/lib/map/map.service.d.ts(5,10): error TS2305: Module '".... /node_modules/rxjs/Observable"' has no exported member 'Observable'**

**Comment by Wykks** [comment]
It works with angular 6, if you use `rxjs-compat`.
For example: https://stackblitz.com/edit/ngx-mapbox-gl-playground

But yeah, of course, I'll update the code base to Angular 6 / rxjs 6 soon enough.

**Comment by Wykks** [comment]
Updated to angular 6 in `2.0.0-beta.0` release.
