### ISSUE TITLE
Angular v13

### ISSUE THREAD

**Issue by Ste-denko** [Wykks/ngx-mapbox-gl#365]
I am getting the following error output when executing  `npm install ngx-mapbox-gl mapbox-gl`:

```
npm ERR! While resolving: mapbox@0.0.1
npm ERR! Found: @angular/common@13.2.7
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.2.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"12.x" from ngx-mapbox-gl@7.1.2
npm ERR! node_modules/ngx-mapbox-gl
npm ERR!   ngx-mapbox-gl@"^7.1.2" from the root project
```

I guess its becaue I got Angular v13.x installed and per documentation ngx-mapbox-gl is only compatible with Angular v12.x (v7.X : Angular 12 (rxjs >= 6.6)).
Will there be a version upgrade?

Thanks and cheers.

**Comment by eschricker** [comment]
@Wykks can you give an update about this?

**Comment by alexmac131** [comment]
I too am using 13 and this is blocking.

**Comment by Wykks** [comment]
Fixed by https://github.com/Wykks/ngx-mapbox-gl/pull/368
