### ISSUE TITLE
Add [(ngModel)] for <mgl-control mglGeocoder>

### ISSUE THREAD

**Issue by ciukstar** [Wykks/ngx-mapbox-gl#37]
Is there a way to specify the model for `<mgl-control mglGeocoder>`?

Scenario:
1) User selects an address from a dialog.
2) ```
dialogRef.afterClosed().subscribe(addr => {
      this.geocoderInput = addr;
      /* this.geocoder.query(addr); */
    });
```

Template:
`<mgl-control mglGeocoder [(ngModel)]="geocoderInput">`

**Comment by Wykks** [comment]
Hi! 

I added `searchInput` as input of `mglGeocoder`, which directly query after changes.
(I can't do two way binding, there's no getInput in https://github.com/mapbox/mapbox-gl-geocoder)
