### ISSUE TITLE
Angular v15

### ISSUE THREAD

**Issue by coman3** [Wykks/ngx-mapbox-gl#387]
Need to update to Angular v15 :)

**Comment by Maximegalon** [comment]
So is it safe to say this project is dead?  I mean, the first/most basic "show a map" example doesn't even work for me.

https://wykks.github.io/ngx-mapbox-gl/demo/display-map

**Comment by Sebi11** [comment]
Probably yes, not much support sadly... But that's how open-source works sometimes! 

For the record, I have an Angular 15 app in which I managed to make Here Maps works, just using [the official guide](https://developer.here.com/documentation/maps/3.1.30.15/dev_guide/topics/angular-practices.html).
