### ISSUE TITLE
So, this library will not going to upgrade to Angular v15, right?

### ISSUE THREAD

**Issue by mehedihasansjs** [Wykks/ngx-mapbox-gl#397]

**Comment by MO-Lewis** [comment]
@devlikhon The library currently supports up to Angular 16, as shown in the README.

**Comment by devlikhon** [comment]
> @devlikhon The library currently supports up to Angular 16, as shown in the README.

Dont know why, but it supports v14 and v16, and skipped v15. Any reason for that?

**Comment by MO-Lewis** [comment]
> Dont know why, but it supports v14 and v16, and skipped v15. Any reason for that?

Not too sure why sorry; I'm personally waiting for Angular 17 support here. I've made my own ticket here: https://github.com/Wykks/ngx-mapbox-gl/issues/410
