### ISSUE TITLE
bug? mgl-layer 'type' is required

### ISSUE THREAD

**Issue by apptum** [Wykks/ngx-mapbox-gl#4]
The wiki doesn't explicit tells that it's required, but more so:
```
LayerComponent {
[...]
  @Input() type?: 'symbol ....'
}
```
- the Input for `type` shouldn't be optional.

Tested with demo/geojson-line : removing `type: "line"` results in no line drawn.

**Comment by Wykks** [comment]
Indeed, I blindly followed `@types/mapbox-gl` there which blindly followed the official spec https://www.mapbox.com/mapbox-gl-js/style-spec#layer-type
Not a big deal, Angular doesn't even check that :smile:
