### ISSUE TITLE
ngx-mapbox-gl vs /Telerik-Verified-Plugins/Mapbox

### ISSUE THREAD

**Issue by ansarikhurshid786** [Wykks/ngx-mapbox-gl#40]
Hi, 
I am developing hybrid app using ionic 3 and angular 4. Which one should i used for ionic application ngx-mapbox-gl vs telerik plugin?

**Comment by Wykks** [comment]
Hi!

I don't know much about Telerik-Verified-Plugins. But it seems this version use the native version of mapbox-gl, which is faster than the js version (used by `ngx-mapbox-gl`).

**Comment by ansarikhurshid786** [comment]
Thanks for quick response.

**Comment by ansarikhurshid786** [comment]
Yesday I was developed app with Telerik-Verified-Plugins/Mapbox but i can seet that it has very few method. 
How can i use other basic methods?

That seem no maintenance.

**Comment by ansarikhurshid786** [comment]
can anyone check Telerik-Verified-Plugins/Mapbox and let me know how to use basic method?

**Comment by Wykks** [comment]
You should post your question about Telerik-Verified-Plugins/Mapbox, here : https://github.com/Telerik-Verified-Plugins/Mapbox/issues
Or at StackOverflow

By the way, after a second look a this, I was wrong. It seems that Telerik-Verified-Plugins/Mapbox also use the js version of mapbox-gl, so I have no idea which is better for you. I don't know much about ionic.
