### ISSUE TITLE
Imports are immutable in JavaScript - esbuild error

### ISSUE THREAD

**Issue by BojanKogoj** [Wykks/ngx-mapbox-gl#403]
I'm trying Jest on Angular 16 which uses esbuild, and get the following error
```
X [ERROR] Cannot assign to import "baseApiUrl"

    node_modules/ngx-mapbox-gl/fesm2022/ngx-mapbox-gl.mjs:34:25:
      34 │                 MapboxGl.baseApiUrl = options.customMapboxApiUrl;
         ╵                          ~~~~~~~~~~

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter function i
```

The issue seems to be [this line](https://github.com/Wykks/ngx-mapbox-gl/blob/main/libs/ngx-mapbox-gl/src/lib/map/map.service.ts#L112). Which is weird, because `baseApiUrl` is [already a setter](https://github.com/mapbox/mapbox-gl-js/blob/main/src/index.js#L121). 
The only solution I found was [modifying request](https://github.com/mapbox/mapbox-gl-js/issues/9740#issuecomment-636129589) instead.

[Issue for introducing error to esbuild](https://github.com/evanw/esbuild/issues/202).

Using
 - Angular 16.1.3
 - ngx-mapbox-gl: 10.0.0
 - mapbox-gl: 2.15.0

**Comment by harellevy** [comment]
Same here...

**Comment by Anakii** [comment]
same for me, also opened an issue https://github.com/Wykks/ngx-mapbox-gl/issues/407

**Comment by BojanKogoj** [comment]
@Wykks Can you please release a new version with this fix?
