### ISSUE TITLE
Prod build Broken Cli 6.0.0-6.0.8

### ISSUE THREAD

**Issue by Magn3s1um** [Wykks/ngx-mapbox-gl#41]
I have a Shared Module which imports NgxMapboxGLModule without calling forRoot.  

The cli builds this package correctly with the --prod flag. 

The app module which uses this shared module imports NgxMapboxGLModule.forRoot().  During production build using

`ng build --prod`

The following error is displayed: 

`ERROR in ./node_modules/@sharedmodule/shared/sharedmodule-shared.ngfactory.js
Module not found: Error: Can't resolve './node_modules/ngx-mapbox-gl/ngx-mapbox-gl.ngfactory' in 'c:\TFS\DataLayers\UI\node_modules\@sharedmodule\shared'`

Any idea what could be causing this, or is version 1.2.0 not ready for optimization with Cli version 6+?

Any idea if cli 6.1 beta would work?

**Comment by Wykks** [comment]
Hum, not sure what's going on.
I'll update `ngx-mapbox-gl` to Angular 6 this week. Hopefully, it'll solve this issue.

**Comment by Magn3s1um** [comment]
Thanks, after some playing around I've  gotten a bit further.  I'll investigate more and provide some insight.

**Comment by Wykks** [comment]
Update done! Please test `2.0.0-beta.0` :)
