### ISSUE TITLE
How to use properties and method of map object. 

### ISSUE THREAD

**Issue by ansarikhurshid786** [Wykks/ngx-mapbox-gl#44]
I am new here. 
Can you help how to basic methods and properties of mapbox object like 
 
map.flyTo({
center:[54,34], 
zoom:17
});

**Comment by Wykks** [comment]
You should not directly think about  "how to use mapbox-gl api", but what you _actually_ want to do.

In your example, you want to the map to a given center with given zoom.
To do this, just change the zoom and center of `mgl-map` 

You can see some example here : https://wykks.github.io/ngx-mapbox-gl/demo/edit/display-map

**Comment by ansarikhurshid786** [comment]
Yes thanks reference and example
