### ISSUE TITLE
Memory leak  possability

### ISSUE THREAD

**Issue by mapsgeek** [Wykks/ngx-mapbox-gl#45]
i have been working with a project involving loading a dashboard lazy loaded module which contains a  map component.
expected behaviour is that once navigate to another modules or children components, the map component should gets destroyed, leaving nothing behind in memory.
what happens is that when you navigate back to the dashboard module, a new instance of the map component along with the map service get initiated causing a rise in memory usage overtime when you navigate through the app different pages, because the map component doesn't get destroyed or garbage collected, reducing performance significantly over time.

![capture](https://user-images.githubusercontent.com/10188264/42123793-30dfd31c-7c58-11e8-830e-c9319e713fe3.JPG)

i experienced this in Angular 5.2.2 using just mapbox-gl 0.46.0, and now when i tried using ngx-mapbox-gl i found the same behaviour.

a reproducing [repo](https://mapbox-with-lazyloading.stackblitz.io)

**Comment by Wykks** [comment]
Interesting! Thanks to you repro, I was able to see it.

But, I can't repro in the version 2.0.0-beta (https://stackblitz.com/edit/mapbox-with-lazyloading-n9mbbs)

So it's probably an issue with angular 5, not clearing lazy loaded components maybe.

**Comment by mapsgeek** [comment]
thanks, but actually i still can reproduce it. please bear with me for a bit
here are my steps

**1.  load the app, take an initial snapshot, size = 45 MB**

**2. navigate to customers, loads customers-list which contains the map, size = 55 MB**
![capture](https://user-images.githubusercontent.com/10188264/42126311-71260bc0-7c86-11e8-9d95-90dc89d3befb.JPG)

**3. navigate back to home, size = 51 MB** 
![capture](https://user-images.githubusercontent.com/10188264/42126340-27e2ebee-7c87-11e8-8c80-02e24f693bf5.JPG)

As you can see compare the snapshot with the previous only  the customerlist component " the map container " got garbage collected, the map Component and service still hanging there.

**4. go back to customer, take a snapshot. size = 59 MB**
and you can see that now the mapcomponent and service each has 2 instances allocated in the memory, because the one from previous navigation didn't get destroyed.
![capture](https://user-images.githubusercontent.com/10188264/42126369-c274722c-7c87-11e8-951a-5944250d238d.JPG)

with each navigation you get a new instance added, accumulate in memory and GPU memory  causing a drastic drop in performance when the app has layers and filters etc... , please tell me if i'm missing or misunderstand something

**Comment by Wykks** [comment]
Yes, inded there's still a small leak apparently. It's better in Angular 6 though. If you go to "Orders", I don't see any instance of `MapComponent` anymore.

I'll see If I can do something about that, but it seems to be a bug in Angular itself

**Comment by mapsgeek** [comment]
the performance might not look dropped in the repo because we just loading the map, when you load vector-tiles layers and query the source features or rendered features with let's say nearly a 1000 feature with their geometry arrays, and apply filters to that, fitbounds, restyle  etc .. , then the app copies and stacks instances of this on top of each other , the performance gets to hit.

i see what you are doing with the `this.mapInstance.remove()` , i tried doing the same as well calling the `.remove()` on the `ngOnDestroy` and even tried to set the map to `undefined` when i was using mapboxGL js raw, then i thought to give your module a shot and here we are with the same behaviour.

i was doubting angular but i see that it destroys the container component !, but now i have no clear vision which side to blame

**Comment by Wykks** [comment]
So `ngOnDestroy` might not be called when the component are still there. Make sense. Will test that.

If this is the case, I may eat a lot more ram than just the extras instance of MapComponent/MapService. But still not hit the performance (at least, while the host does have free ram), because the cpu/gpu _are not_ affected by that.

**Comment by mapsgeek** [comment]
![0 44](https://user-images.githubusercontent.com/10188264/42133109-740c830c-7d24-11e8-9ffb-9fccb02acc49.gif)

after a while the map goes from the 60fps smooth transitions to that lag and spikes in zoom in and out, this in chrome, the case goes worth in firefox and edge, and not in my app or angular only.
opening any example from the docs in firefox and i don't even get near to the 60fps chrome shows when the app is fresh, would you consider this a performance issue ? of course there's no continuous high cpu usage, just on zoom in and out, and for the gpu process in chrome task manager it gets close to 1GB in memory footprint and 350MB in gpu memory and the app tab can reach 800MB of memory footprint and  those are all the info i can get since i don't have enough knowledge of memory to debug this further more

**Comment by Wykks** [comment]
Okay one issue at a time :sweat_smile: 
The map is lagging after using it for a while ? I guess this should be reported to the mapbox-gl repo!

I'll try to see what's going on about Angular not destroying the map component, but not about map lagging after a while

**Comment by mapsgeek** [comment]
thanks, sorry if i'm mixing things here but i think i'm getting this lag because of that no destruction thing !

**Comment by Wykks** [comment]
Note to self: http://plasma-umass.org/BLeak/

**Comment by mapsgeek** [comment]
don't provide the map service as a singleton in the shared module otherwise it will never get destroyed, instead provide in component providers... now i can die in peace

https://netbasal.com/angular-services-do-not-have-to-be-singletons-ffa879e62082

**Comment by Wykks** [comment]
I'm not sure how it relate to this issue.
In the repro example here : https://stackblitz.com/edit/mapbox-with-lazyloading (not working anymore, but still) the map service is only provided in the map component.

I sometimes see people providing MapService in a module for unknown reason. It could be useful to add a warning in ngx-mapbox-gl if MapService is provided in a module.
MapService was actually private before this issue https://github.com/Wykks/ngx-mapbox-gl/issues/19#issuecomment-361069379 . I should have made a more fine grained access to MapService...

**Comment by mapsgeek** [comment]
hmmm you are right, well here's the full story i used to provide services in modules without thinking in the consequence like mentioned on that article, when i read the article i got a flash back that i used to do that with mapbox gl so that's what was going wrong,  i didn't test well before i make that comment and depended on augury inspection to make sure that the component and service has been destroyed but then now when i ran heapSnapShot at different lifecycles, the memory still have the map component and the service, i'm not an expert in debugging memory stuff but i click garbage collect button before i take a snap shot, i remember that once but not sure i tried the same process on vuejs and it was the same.
![image](https://user-images.githubusercontent.com/10188264/57197349-8cbc2a80-6f66-11e9-9447-f312daf712c4.png)
