### ISSUE TITLE
GeoJSON namespace missing

### ISSUE THREAD

**Issue by mrkking** [Wykks/ngx-mapbox-gl#47]
after installing and add to app.module - multiple errors appear :'Cannot find namespace "GeoJSON"

**Comment by i-am-Chandan-Shaw** [comment]
Hello everyone, I faced a similar issue : 
"node_modules/maplibre-gl/dist/maplibre-gl.d.ts:6033:65 - error TS2503: Cannot find namespace 'GeoJSON'." 

My solution was simple, I went on to all the files manually from node modules and tried resolving each error one by one. For me it worked by installing two packages in which it was showing the error:

1) npm i --save-dev @types/mapbox__vector-tile
2) npm i --save-dev @types/mapbox__point-geometry

If any other problem persists go to the fille and hover over the problem to get the issue and then solve it.
