### ISSUE TITLE
popup [lngLat] binding removes and adds marker causing close events to fire unnecessarily

### ISSUE THREAD

**Issue by antonsimola** [Wykks/ngx-mapbox-gl#48]
Hi, first of all thanks for great library!

I noticed that I get some unwanted events fired for the popup `(close)` event. I believe that is because you are removing and adding the popup again to the map with the updated lnglat value. Could it be possible to use the underlying popup's `setLngLat `function instead? this should also update the map without firing the close events, I believe.

On a second note, have you considered adding mapbox gl draw library bindings? I might be able to help with that as well as I'm doing something with the draw library right now.

**Comment by Wykks** [comment]
Hi!

I was using `setLngLat` before but I changed this to be easier to use (https://github.com/Wykks/ngx-mapbox-gl/commit/1ca82c1).
I'll think about a better way. One solution is to not send close event in this situation.

About mapbox-gl draw, yep, but I need more motivation :sweat_smile:

**Comment by antonsimola** [comment]
Oh I see. I try to test on Monday if reverting to the version before that commit fixes the issue for me. I'm on 1.2. I think your idea seems great, filter out close event in ngOnChanges should do the trick, that way you can continue using remove/add technique.
