### ISSUE TITLE
map is not displaying

### ISSUE THREAD

**Issue by kevin0898** [Wykks/ngx-mapbox-gl#49]
Hello,

I'm in a project with Angular 6 and I'm using the library but the map is not displaying and it does not give any errors, is anyone else going through this?

**Comment by MiguelMtzP** [comment]
I had exactly the same problem, but I had just forgotten put the style 
```
mgl-map {
      height: 100%;
      width: 100%;
    }
```

**Comment by mapsgeek** [comment]
due to certain css rules regarding the container that holds the map sometimes a 
` #map {
   height:100%
}`
don't work for me  so consider set the `height` in `px` just to see if this is where the issue is coming from

**Comment by libyapages** [comment]
Same issue with { height:100% }, I had to specify it in pixel instead.

**Comment by MTRNord** [comment]
PS instead of 

```
mgl-map {
    height: 100%;
    width: 100%;
}
```

you can use

```
mgl-map {
  height: 100vh;
}
```

It has the same effect.

To remove the border around the map you can use

```
body {
  margin: 0;
}
```
