### ISSUE TITLE
Does not compile with mapbox-gl & @types/mapbox-gl version 0.48.0

### ISSUE THREAD

**Issue by dmytro-gokun** [Wykks/ngx-mapbox-gl#56]
The result is this error:

> ERROR  in node_modules/ngx-mapbox-gl/lib/source/geojson/geojson-source.component.d.ts(2,10): error TS2305: Module '"node_modules/@types/mapbox-gl/index"' has no exported member 'GeoJSONGeometry'.

**Comment by r6047736** [comment]
Same here

**Comment by vinaykumarreddysoddala** [comment]
Same Here 

Can anyone tell how to fix these error

**Comment by polaris327** [comment]
For me as well.

**Comment by Diaaz** [comment]
Same here

**Comment by aprilmay** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28338/files

Until this is fixed, try with the previous version of @types/mapbox-gl, eg:

> yarn add --dev @types/mapbox-gl@0.47.2

**Comment by Wykks** [comment]
Fixed in v2.1.0
