### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by LennyZ71** [Wykks/ngx-mapbox-gl#58]
@Wykks 
I'm using this current WeatherImageryFeed.  I'm curious about it's rendering performance.  It's so slow.  Is there a better way to retrieve it or could there be a bug in mapbox-gl?  
Thanks
```
<mgl-raster-source
         id="radar"
         [tiles] = "['https://nowcoast.noaa.gov/arcgis/services/nowcoast/radar_meteo_imagery_nexrad_time/MapServer/WmsServer?bbox={bbox-epsg-3857}&service=WMS&request=GetMap&version=1.3.0&layers=1&styles=&format=image/png&transparent=true&height=256&width=256&crs=EPSG:3857']"
         [tileSize] = "256">
       </mgl-raster-source>
```

**Comment by Wykks** [comment]
Hi!

It could be an issue inside mapbox-gl or in your service.
I dont think there's a better way to load raster source in mapbox-gl.

Try to post your issue to mapbox-gl
