### ISSUE TITLE
Geocoder result event firing twice after searching for a second address

### ISSUE THREAD

**Issue by jh-code** [Wykks/ngx-mapbox-gl#59]
I have a geocoder on my map that is used to place markers on a map. If I search for an address, select the right one, it adds a marker to the map at that location. If I delete the text in the search input and search for another address, then select it, I get an event for the previous address and the new one. It works as expected if I manually click the x to clear the search input, but not if I highlight/erase the text in the input.

Is this expected behavior? If so, how can I clear the search input programmatically?

**Comment by jh-code** [comment]
I was able to work around it by doing this for now

`this.addresses.controls = this.addresses.controls.filter((address): boolean => address.value['id'] !== ev.results.id);`

**Comment by Wykks** [comment]
That's a know bug : https://github.com/mapbox/mapbox-gl-geocoder/issues/99
I'll add a workaround inside ngx-mapbox-gl
