### ISSUE TITLE
bug:<mgl-geojson-source> error when routing away before map has loaded

### ISSUE THREAD

**Issue by apptum** [Wykks/ngx-mapbox-gl#6]
Reproduce:
- add a `<mgl-geojson-source id="symbols-source"></mgl-geojson-source>` to a map (doesn't madder if w or w/o `<mgl-feature>`.
- rout away from page with map before map has fully loaded.
- Error:
```
Error: Uncaught (in promise): TypeError: Cannot read property 'unsubscribe' of undefined
TypeError: Cannot read property 'unsubscribe' of undefined
    at GeoJSONSourceComponent.ngOnDestroy (geojson-source.component.ts:79)
````

**Comment by Wykks** [comment]
Oh wow, I usually doesn't do this kind of mistake :(

Thanks for finding that out
