### ISSUE TITLE
Change language?

### ISSUE THREAD

**Issue by Saerdn** [Wykks/ngx-mapbox-gl#61]
Hey,

I'm successfully using your wrapper but I need to change the language of the map. I couldn't find anything in your documentation. Any hints on where to start?
I tried to work with the layout property as suggested in the mapbox documentation (https://www.mapbox.com/mapbox-gl-js/example/language-switch/) thou the only property with "layout" I found was for the layer component.

Thank you, 
Andi

**Comment by Saerdn** [comment]
I actually found a solution (in your documentation: https://wykks.github.io/ngx-mapbox-gl/demo/language-switch
I switched from buttons to auto set the language:
`
    set map(mapInstance: Map) {
        mapInstance.setLayoutProperty('country-label-lg', 'text-field', '{name_de}');
    }`

However, it would nice if one could set it via property, wouldn't it?

**Comment by Wykks** [comment]
Hi!

I can't set this as a prop because I depends of want you want to do:
Which layer do you want to translate, as long as your vector source actually support multiple language.(because not everyone is using `mapbox://styles/mapbox/light-v9` as a source).
