### ISSUE TITLE
Geocoder does not show suggestions

### ISSUE THREAD

**Issue by osca** [Wykks/ngx-mapbox-gl#62]
I tried to use geocoding with an input in my project like this:
`
<mgl-map [style]="'mapbox://styles/mapbox/streets-v9'" [zoom]="[9]">
          <mgl-control mglGeocoder></mgl-control>
</mgl-map>
`

The input shows up and i can type something into it. It also starts the HTTP request to mapbox and also getting the response: 
`
{"type":"FeatureCollection","query":["new","york"],"features":[{"id":"place.15278078705964500","type":"Feature","place_type":["place"],"relevance":1,"properties":{"wikidata":"Q60"},"text":"New York","place_name":"New York, New York, United States","bbox":[-74.2590879797556,40.477399,-73.7008392055224,40.917576401307],"center":[-73.9808,40.7648],"geometry":{"type":"Point","coordinates":[-73.9808,40.7648]},"context":[{"id":"region.3866","short_code":"US-NY","wikidata":"Q1384","text":"New York"},{"id":"country.3145","short_code":"us","wikidata":"Q30","text":"United States"}]},{"id":"region.3866","type":"Feature","place_type":["region"],"relevance":1,"properties":{"short_code":"US-NY","wikidata":"Q1384"},"text":"New York","place_name":"New York, United States","bbox":[-79.762418,40.420528,-71.678024,45.015865],"center":[-76.301667,42.685498],"geometry":{"type":"Point","coordinates":[-76.301667,42.685498]},"context":[{"id":"country.3145","short_code":"us","wikidata":"Q30","text":"United States"}]},{"id":"poi.2442863","type":"Feature","place_type":["poi"],"relevance":1,"properties":{"tel":"(212) 630-6401","address":"1 Penn Plz","category":"rail station, train station","landmark":true,"wikidata":"Q54451","maki":"rail"},"text":"New York Penn Station","place_name":"New York Penn Station, 1 Penn Plz, New York, New York 10119, United States","center":[-73.99283,40.750813],"geometry":{"type":"Point","coordinates":[-73.99283,40.750813]},"context":[{"id":"neighborhood.290417","text":"Garment District"},{"id":"locality.12696928000137850","wikidata":"Q11299","text":"Manhattan"},{"id":"postcode.14586990685738040","text":"10119"},{"id":"place.15278078705964500","wikidata":"Q60","text":"New York"},{"id":"region.3866","short_code":"US-NY","wikidata":"Q1384","text":"New York"},{"id":"country.3145","short_code":"us","wikidata":"Q30","text":"United States"}]},{"id":"poi.2485372","type":"Feature","place_type":["poi"],"relevance":1,"properties":{"tel":"(212) 788-9600","address":"260 E Broadway","category":"landmark","landmark":true,"wikidata":"Q1065206","maki":"monument"},"text":"New York City Hall","place_name":"New York City Hall, 260 E Broadway, New York, New York 10007, United States","center":[-74.00588,40.712658],"geometry":{"type":"Point","coordinates":[-74.00588,40.712658]},"context":[{"id":"neighborhood.2103005","text":"Tribeca"},{"id":"locality.12696928000137850","wikidata":"Q11299","text":"Manhattan"},{"id":"postcode.1858844876027420","text":"10007"},{"id":"place.15278078705964500","wikidata":"Q60","text":"New York"},{"id":"region.3866","short_code":"US-NY","wikidata":"Q1384","text":"New York"},{"id":"country.3145","short_code":"us","wikidata":"Q30","text":"United States"}]},{"id":"poi.2264121","type":"Feature","place_type":["poi"],"relevance":1,"properties":{"tel":"(718) 694-1600","address":"Boerum Pl","category":"museum","landmark":true,"wikidata":"Q1503777","maki":"museum"},"text":"New York Transit Museum","place_name":"New York Transit Museum, Boerum Pl, New York, New York 11201, United States","center":[-73.98996,40.690468],"geometry":{"type":"Point","coordinates":[-73.98996,40.690468]},"context":[{"id":"neighborhood.297509","text":"Downtown"},{"id":"locality.6335122455180360","wikidata":"Q18419","text":"Brooklyn"},{"id":"postcode.15332151625363130","text":"11201"},{"id":"place.15278078705964500","wikidata":"Q60","text":"New York"},{"id":"region.3866","short_code":"US-NY","wikidata":"Q1384","text":"New York"},{"id":"country.3145","short_code":"us","wikidata":"Q30","text":"United States"}]}],"attribution":"NOTICE: © 2018 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained."}
`

But the suggestions does not show up and the loading icon is spinning infinitely.
Does anyone have any idea how to get it work?

I'm using following versions in my package.json:
`
"@angular/core": "6.1.7",
...
"mapbox-gl": "^0.48.0",
"ngx-mapbox-gl": "^2.1.0",
...
"rxjs": "^6.1.0",
...
"@types/mapbox-gl": "^0.48.0",
`

Thanks in advance for help!

**Comment by Wykks** [comment]
Hi!

Can you reproduce your issue here ?
https://stackblitz.com/edit/angular-ikgtnh

**Comment by ThomasLohmann** [comment]
@Wykks is it possible to show just the search for autocomplete without the map and bind the selected location to a reactive form input? (e.g. the same add Location functionality like on Instagram)

Kind regards,
Thomas

**Comment by agtzdimi** [comment]
I am facing the same problem. @osca did you find a sollution on that?

**Comment by osca** [comment]
@agtzdimi, yes, not a perfect solution, but at least I found the problem. I was using

`"pace-js": "1.0.2",`

as a dependency. That caused the problem for me. As a workaround, I removed the dependency and added it manually to my javascript assets. If you don't use pace-js, you have to find the conflicting dependency or script. I removed the scripts and styles in my angular.json file one by one and figured it out this way.

I hope this helps for you as well.

@Wykks, maybe you can figure out a solution for that, as it is now reproducible.

**Comment by agtzdimi** [comment]
I can confirm `"pace-js": "1.0.2"` was the issue. I have also removed and it worked.
Thank you @osca
