### ISSUE TITLE
Is there a way to place the geocoder input outside the map?

### ISSUE THREAD

**Issue by bgail** [Wykks/ngx-mapbox-gl#68]
Is there a way to place the geocoder input outside the map?
Where can I find more docs about

<mgl-control
        mglGeocoder
</mgl-control>

**Comment by Wykks** [comment]
Hi,

Not now, but it's something that may be added.

Doc need to be added in the wiki. For now, you can look here: 
https://github.com/Wykks/ngx-mapbox-gl/blob/master/projects/ngx-mapbox-gl/src/lib/control/geocoder-control.directive.ts#L47
And here:
https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md

**Comment by tudor2004** [comment]
What if I instantiate the geocoder object in my typescript file, how can I move a marker on the map based on the returned event?

```
var geocoder = new MapboxGeocoder({
            accessToken: mapboxgl.accessToken
        });
```
