### ISSUE TITLE
mgl-marker-cluster data is not actually dynamic

### ISSUE THREAD

**Issue by bytelabsco** [Wykks/ngx-mapbox-gl#71]
I'm using mgl-marker-cluster with geojson that is generated in my component controller.  Whenever I update information in the variable bound to the data property of mgl-marker-cluster, the map will not update.  I've tried editing the data in place (same variable reference) and creating a completely new set of data (changing the reference) but the map will not update without some manual interaction with the map (pan, zoom, etc).

The only workaround I've found is the old school hacky method where you set the variable to null, then set it to the new value in a setTimeout() call.  However, this creates an undesirable flicker.   Any suggestions?

**Comment by Wykks** [comment]
Totally my bad, now fixed... Sorry for the delay :confounded:
