### ISSUE TITLE
Order of controls in same position is not respected

### ISSUE THREAD

**Issue by sroettering** [Wykks/ngx-mapbox-gl#75]
When placing multiple control elements in the same position (e.g. 'top-right') the order in which they are declared in the component template is not respected.
I prepared this demo https://stackblitz.com/edit/angular-xfbv8d?file=demo.ts where I add a navigation control without a compass below a custom control but the order is ignored.
When I add a navigation control in the "load" callback I can, however, define an order.

Unfortunately, this is a difficult workaround if there are a lot of custom controls which should have a defined order.

**Comment by dmytro-gokun** [comment]
Same issue here

**Comment by dmytro-gokun** [comment]
@Wykks I will work on this
