### ISSUE TITLE
Updating layer filter does not update the map

### ISSUE THREAD

**Issue by mrpdean** [Wykks/ngx-mapbox-gl#81]
When I initially set the layers filter it works:

`this.heatmapLayer.filter = ['==', 'month', 11];`

However when I subsequently set the filter again, for example on a button click event, the map is not updated to reflect the new filter.

`this.heatmapLayer.filter = ['==', 'month', 6];`

No errors are generated but the map does not update.

Thanks

**Comment by Wykks** [comment]
You must change the reference of anything you pass to ngx-mapbox-gl anytime you make a change.
To support your use case, I would need to add ngDoCheck everywhere which is not good performance wise, and definitely not a good practice.

**Comment by mrpdean** [comment]
Thanks.  I still can't get it to update using your example above but I'm probably doing something wrong.  Very new to Angular.  I'll keep trying.
