### ISSUE TITLE
Problem with latest version in npm repository

### ISSUE THREAD

**Issue by dmytro-gokun** [Wykks/ngx-mapbox-gl#83]
There must be some problem with npm deployment of the package as it says that version 1.2.2 is latest, not 2.3.0 as it should be. Here: https://www.npmjs.com/package/ngx-mapbox-gl

**Comment by Wykks** [comment]
Yup just noticed that, npm show as latest the last version published... I'll fix that asap

**Comment by Wykks** [comment]
Fixed by releasing `2.3.1` (no changes)
