### ISSUE TITLE
Click handler on layer not working

### ISSUE THREAD

**Issue by bdirito** [Wykks/ngx-mapbox-gl#84]
The demo

https://wykks.github.io/ngx-mapbox-gl/demo/center-on-symbol

does not seem to be working. The layer click handler does not trigger and the mouseEnter & mouseLeave events do not seem to be firing. 

Chrome 70
![click_hover](https://user-images.githubusercontent.com/8117238/49764774-a5613680-fc8d-11e8-81de-f9f1343af9ff.png)

**Comment by bdirito** [comment]
It looks like this might have been broken in the fix to my other issue 

https://github.com/Wykks/ngx-mapbox-gl/commit/99a5bb716f0e4472b022dac19e05ab0a99063690#diff-29fb98d58b4b6b0d9d914fcd11de79e3
```
        startWith(true),
        filter(() => !this.MapService.mapInstance.getLayer(this.id)),
        mapTo(false)
```

Im not a rx expert but to me this implys that the startWith(true) will run though the mapTo(false) meaning that there will never be a call with true.  Without fully understanding ngx-mapbox-gl perhaps you want
```
  filter()
  mapTo()
  startWith()
```

**Comment by dmytro-gokun** [comment]
Same here

**Comment by Wykks** [comment]
Sorry, I refactored a bit too fast there :worried:
