### ISSUE TITLE
Properties from click event and mouse enter are not the same

### ISSUE THREAD

**Issue by hnahoulder** [Wykks/ngx-mapbox-gl#89]
Hello,

I use the MapMouseEvent to get the properties of my objects in the layer. So when the mouse enter on one object, I have the propeties: features, lngLat, originalEvent, point, target and type; but when I use the click event on my object, why the property features is missing?

**Comment by Wykks** [comment]
It's there, look at the demo : https://wykks.github.io/ngx-mapbox-gl/demo/edit/popup-on-click

But there's was a typescript issue; now fixed :)
