### ISSUE TITLE
Not displayed inside angular material component

### ISSUE THREAD

**Issue by Matthis2909** [Wykks/ngx-mapbox-gl#93]
Hi, 

I want use mapbox-gl inside my angular project. When I build my map inside app.component.html it works but when I want display her inside another component this map don't showing up and I haven't error on my console. 

Can you help me ?

My component.ts

>   buildMap(){
      let map = new mapboxgl.Map({
          container: 'map',
          style: this.style,
          zoom: 16,
          center: [-122, 37]
      });
  }
My component.html

> <div id="map-container">
  <div id='map' style='width: 100%; height: 100%;'></div>
</div>

I think it's lifecycle of my component but I don't really know

**Comment by sroettering** [comment]
You don't have to create a `mapboxgl.Map` yourself. Just add
```
<mgl-map [style]="style" [zoom]="zoom" [center]="center">
</mgl-map>
```
to the `MyComponent.html` template.
Maybe you have to specify some width and height for the `mgl-map` element.
