### ISSUE TITLE
Integrating localGeocoder with local data source

### ISSUE THREAD

**Issue by juliandamass** [Wykks/ngx-mapbox-gl#94]
Hi, need help is there any way to do the localGeocoder like this = https://docs.mapbox.com/mapbox-gl-js/example/forward-geocode-custom-data/ using this Wykks/ngx-mapbox-gl?
Thanks a lot

**Comment by juliandamass** [comment]
Thank for reply
Yes i see it, but can give some code example to implement “localGeocoder” control?
Like this example, https://docs.mapbox.com/mapbox-gl-js/example/forward-geocode-custom-data/

**Comment by ciukstar** [comment]
It's not an working example, but the main idea is to pass the map with `(load)="onMapLoad($event)"` then use the map as in the example you provided.
```
<mgl-map [accessToken]="token"
      [style]="style" [zoom]="zoom" [interactive]="true"
      (load)="onMapLoad($event)">
...
...
</mgl-map>
```

```
import { Component, OnInit } from '@angular/core';
import { Map as MapboxMap } from 'mapbox-gl';
import * as MapboxGeocoder from '@mapbox/mapbox-gl-geocoder';
....

@Component({...}
export class SomeComponent implements OnInit {
  ...
  token: string;
  style: string;
  zoom: number[];
  ...
  constructor() {
    this.token = ...
   this.style = ...
   this.zoom = [8];
  }
  ...
  ngOnInit() {
    ...
  }
  ...
   onMapLoad(map: MapboxMap) {
      map.addControl(new MapboxGeocoder({
      accessToken: token,
      localGeocoder: forwardGeocoder,
      zoom: 14,
      placeholder: "Enter search e.g. Lincoln Park"
    }));
  }
  ...
  ...
}
```

**Comment by juliandamass** [comment]
Thank you, thank you very much. Working like a charm.
I am so sorry, i still new in Angular and TypeScript

**Comment by ciukstar** [comment]
You are welcome. Do not forget to close the issue as resolved.
