### ISSUE TITLE
updating [style] object not triggering changes

### ISSUE THREAD

**Issue by bryandesigning** [Wykks/ngx-mapbox-gl#95]
I've stored my custom style as an object and passed it in to the map via [style]=""

However, after the initial load, I'm trying to make style changes (it's listed as a dynamic input) and they're not being reflected in the map. Only changes that are done before the initial load are reflected.

**Comment by bryandesigning** [comment]
Yes, this is what I'm doing essentially.

I've solved this by calling the mapbox gl function directly to change the layer opacity on everything, however, it's a hacky work-around

**Comment by Wykks** [comment]
Cannot reproduce. This example is doing fine : http://localhost:4200/demo/edit/set-style (although it's using a string in the example, but it shouldn't change anything).

Can you reproduce the issue in a stackblitz ?

**Comment by bryandesigning** [comment]
I solved this by calling the mapbox functions directly, unfortunately I simply don't have time to create a repo project as our delivery deadline is within the next month 😞
